// =============================================================================
// ReviewPulse — Seed Data
// =============================================================================
// Realistic seed data for the ReviewPulse demo: ~50 user reviews about a
// Spotify-like music streaming app, with a heavy focus on MUSIC DISCOVERY
// pain points (the project's core mission). Each review ships with pre-computed
// AI analysis fields so the dashboard renders rich data on first load without
// needing to run the AI processor.
//
// Exports:
//   - SeedReviewDef                 — shape of one seed review
//   - SEED_REVIEWS                  — 50 hand-written reviews (see file header)
//   - SeedCollectorSourceDef        — shape of one seed collector source
//   - SEED_COLLECTOR_SOURCES        — 4 default collector sources (one per type)
//   - seedDatabase(db)              — wipes DB and inserts 1 project + reviews + sources
//
// Importing this module has NO side effects. Only calling `seedDatabase(db)`
// writes to the database.
//
// Review distribution (target met):
//   Sources:     google_play 14 · app_store 14 · reddit 12 · twitter 8 · csv_upload 2
//   Themes:      music_discovery 14 · recommendation_quality 8 · playback_bug 6 ·
//                playlist_fatigue 5 · ui_ux 4 · search 3 · offline_mode 3 ·
//                pricing 3 · social_features 2 · audio_quality 2
//   Ratings:     1★ 15 · 2★ 18 · 3★ 9 · 4★ 5 · 5★ 3   (skewed negative — pain-point project)
//   Sentiments:  negative 33 · mixed 8 · positive 6 · neutral 3
// =============================================================================

import { createHash } from "crypto";
import type { PrismaClient } from "@prisma/client";

// -----------------------------------------------------------------------------
// Types
// -----------------------------------------------------------------------------

export interface SeedReviewDef {
  text: string;
  title: string | null;
  rating: number; // 1-5
  source: "google_play" | "app_store" | "reddit" | "twitter" | "csv_upload";
  author: string;
  daysAgo: number; // how many days ago the review was posted
  // Pre-computed AI analysis fields:
  sentiment: "positive" | "negative" | "neutral" | "mixed";
  sentimentScore: number; // 0-1
  theme: string; // snake_case
  subTheme: string;
  priority: "critical" | "high" | "medium" | "low";
  priorityReason: string;
  summary: string;
  keyPhrases: string[];
  isBug: boolean;
  isFeatureRequest: boolean;
  isActionable: boolean;
}

export interface SeedCollectorSourceDef {
  sourceType: "google_play" | "app_store" | "reddit" | "twitter";
  name: string;
  config: string; // JSON-encoded config
  enabled: boolean;
  schedule: string; // cron
  lastRunAt: Date;
  lastRunStatus: "success" | "partial" | "failed";
  lastRunCount: number;
  totalCollected: number;
}

const MS_PER_DAY = 86_400_000;
const MS_PER_HOUR = 3_600_000;
const now = Date.now();
const hoursAgo = (h: number) => new Date(now - h * MS_PER_HOUR);

// -----------------------------------------------------------------------------
// SEED_REVIEWS
// -----------------------------------------------------------------------------
// 50 realistic reviews grouped by source. Authors are plausible usernames;
// titles are short and realistic (Play Store / App Store always have titles,
// Reddit posts have titles / Reddit comments and Twitter posts use null).
// -----------------------------------------------------------------------------

export const SEED_REVIEWS: SeedReviewDef[] = [
  // ===== Google Play (14) ====================================================
  {
    text: "Discover Weekly used to be the best part of Spotify but now it just recycles the same 30 songs every week. I've heard all of them already. Why even bother? Fix this.",
    title: "Discover Weekly is broken",
    rating: 1,
    source: "google_play",
    author: "Marcus T.",
    daysAgo: 3,
    sentiment: "negative",
    sentimentScore: 0.92,
    theme: "music_discovery",
    subTheme: "discover_weekly_repetition",
    priority: "high",
    priorityReason: "Flagship discovery feature failing for engaged user; recurring complaint pattern across sources.",
    summary: "Discover Weekly recycles the same 30 songs weekly; user feels the feature is broken.",
    keyPhrases: ["Discover Weekly", "recycles", "same 30 songs", "every week"],
    isBug: false,
    isFeatureRequest: false,
    isActionable: true,
  },
  {
    text: "I feel like I'm stuck in a bubble. The algorithm just feeds me variations of what I already listen to. I want to actually discover new artists, not more of the same.",
    title: "Stuck in a music bubble",
    rating: 2,
    source: "google_play",
    author: "Priya K.",
    daysAgo: 5,
    sentiment: "negative",
    sentimentScore: 0.85,
    theme: "music_discovery",
    subTheme: "filter_bubble",
    priority: "high",
    priorityReason: "Direct articulation of the core discovery pain point this project targets.",
    summary: "User feels trapped in a recommendation bubble; wants genuine new-artist discovery.",
    keyPhrases: ["stuck in a bubble", "algorithm", "discover new artists", "more of the same"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },
  {
    text: "I love that Spotify has genre playlists but finding them is a pain. Once you stumble onto a good niche like lo-fi jazz or indie folk, it's great. Just wish it was easier to find new genres in the first place.",
    title: "Great when you find niches",
    rating: 4,
    source: "google_play",
    author: "Derek L.",
    daysAgo: 8,
    sentiment: "mixed",
    sentimentScore: 0.55,
    theme: "music_discovery",
    subTheme: "genre_exploration",
    priority: "medium",
    priorityReason: "Positive engagement with a clear discoverability improvement opportunity.",
    summary: "User enjoys niche genre playlists once found but finds discovering new genres difficult.",
    keyPhrases: ["genre playlists", "lo-fi jazz", "indie folk", "find new genres"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },
  {
    text: "App crashes every time I open it on my Galaxy S22. Reinstalled twice, cleared cache, nothing works. Used to love this app, now I can't even use it.",
    title: "Crashes on launch",
    rating: 1,
    source: "google_play",
    author: "Brittany M.",
    daysAgo: 1,
    sentiment: "negative",
    sentimentScore: 0.95,
    theme: "playback_bug",
    subTheme: "launch_crash",
    priority: "critical",
    priorityReason: "Complete app failure on a common device model despite reinstall/cache clear.",
    summary: "App crashes on launch on Galaxy S22 despite reinstall and cache clear.",
    keyPhrases: ["crashes", "Galaxy S22", "reinstalled", "cleared cache"],
    isBug: true,
    isFeatureRequest: false,
    isActionable: true,
  },
  {
    text: "Premium went up again and now there's ads in podcasts too? You're pushing me to Apple Music. The free tier is also basically unusable with the ad frequency now.",
    title: "Pricing keeps climbing",
    rating: 2,
    source: "google_play",
    author: "Tomás R.",
    daysAgo: 12,
    sentiment: "negative",
    sentimentScore: 0.88,
    theme: "pricing",
    subTheme: "price_increase",
    priority: "medium",
    priorityReason: "Pricing churn risk; user explicitly names a competitor alternative.",
    summary: "User frustrated by Premium price hikes and podcast ads; considering Apple Music.",
    keyPhrases: ["Premium went up", "ads in podcasts", "Apple Music", "free tier"],
    isBug: false,
    isFeatureRequest: false,
    isActionable: true,
  },
  {
    text: "Remember when Spotify actually showed you random cool stuff? Now everything is so calculated. I miss the serendipity. Give me a 'surprise me' button or something.",
    title: "Where's the serendipity?",
    rating: 2,
    source: "google_play",
    author: "Hannah W.",
    daysAgo: 6,
    sentiment: "negative",
    sentimentScore: 0.8,
    theme: "music_discovery",
    subTheme: "lack_of_serendipity",
    priority: "medium",
    priorityReason: "Feature gap request directly aligned with the discovery mission.",
    summary: "User misses serendipitous discovery; wants a 'surprise me' feature.",
    keyPhrases: ["serendipity", "calculated", "surprise me", "random cool stuff"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },
  {
    text: "I liked ONE classical piece and now my recommendations are flooded with classical music. The algorithm doesn't understand context. Annoying.",
    title: "One song ruined my recommendations",
    rating: 2,
    source: "google_play",
    author: "Oliver B.",
    daysAgo: 9,
    sentiment: "negative",
    sentimentScore: 0.83,
    theme: "recommendation_quality",
    subTheme: "context_insensitive",
    priority: "high",
    priorityReason: "Algorithm quality complaint; likely affects many users with diverse taste.",
    summary: "Single liked classical song floods recommendations; algorithm lacks context.",
    keyPhrases: ["classical piece", "flooded", "algorithm doesn't understand", "context"],
    isBug: false,
    isFeatureRequest: false,
    isActionable: true,
  },
  {
    text: "Daily Mix 1-6 have been basically the same for 6 months. Same songs, same order. They were great at first. Now they're just background noise.",
    title: "Daily Mix needs refresh",
    rating: 3,
    source: "google_play",
    author: "Jasmine P.",
    daysAgo: 4,
    sentiment: "mixed",
    sentimentScore: 0.6,
    theme: "playlist_fatigue",
    subTheme: "daily_mix_stale",
    priority: "medium",
    priorityReason: "Engaged user reporting staleness on a flagship personalization feature.",
    summary: "Daily Mixes have remained static for 6 months; user finds them stale.",
    keyPhrases: ["Daily Mix", "same for 6 months", "background noise", "stale"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },
  {
    text: "Downloaded playlists for my flight and they wouldn't play offline. Just sat there loading forever. This is the third time this has happened. I pay for Premium specifically for this feature.",
    title: "Offline downloads don't work",
    rating: 1,
    source: "google_play",
    author: "Kenji S.",
    daysAgo: 2,
    sentiment: "negative",
    sentimentScore: 0.94,
    theme: "playback_bug",
    subTheme: "offline_playback_failure",
    priority: "critical",
    priorityReason: "Premium feature failure; reproducible across multiple attempts.",
    summary: "Downloaded playlists fail to play offline; recurring issue for Premium subscriber.",
    keyPhrases: ["Downloaded playlists", "flight", "offline", "loading forever", "Premium"],
    isBug: true,
    isFeatureRequest: false,
    isActionable: true,
  },
  {
    text: "The new UI is confusing. Library is hidden, I can't find my playlists easily, and the home screen is cluttered with podcasts I don't care about. Please simplify.",
    title: "UI getting worse",
    rating: 3,
    source: "google_play",
    author: "Frank D.",
    daysAgo: 15,
    sentiment: "neutral",
    sentimentScore: 0.45,
    theme: "ui_ux",
    subTheme: "navigation_confusion",
    priority: "medium",
    priorityReason: "Usability regression with multiple specific complaints.",
    summary: "User finds new UI confusing; library hidden and home cluttered with podcasts.",
    keyPhrases: ["new UI", "Library is hidden", "cluttered", "podcasts", "simplify"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },
  {
    text: "I actually found an amazing indie artist through Release Radar last week and now I'm obsessed. When Spotify works, it really works. Just wish this happened more often!",
    title: "Release Radar delivered",
    rating: 5,
    source: "google_play",
    author: "Aisha N.",
    daysAgo: 7,
    sentiment: "positive",
    sentimentScore: 0.88,
    theme: "music_discovery",
    subTheme: "release_radar_success",
    priority: "low",
    priorityReason: "Positive feedback; informational only.",
    summary: "User discovered a new indie artist via Release Radar; wishes for more frequent success.",
    keyPhrases: ["Release Radar", "indie artist", "obsessed", "works"],
    isBug: false,
    isFeatureRequest: false,
    isActionable: false,
  },
  {
    text: "Why is the max bitrate still so low? On a good sound system you can really tell. Tidal sounds way better for the same price. Please add lossless already.",
    title: "Where's lossless?",
    rating: 2,
    source: "google_play",
    author: "Marcus H.",
    daysAgo: 20,
    sentiment: "negative",
    sentimentScore: 0.78,
    theme: "audio_quality",
    subTheme: "low_bitrate",
    priority: "low",
    priorityReason: "Long-standing request; competitive gap, not core to the discovery mission.",
    summary: "User complains about low max bitrate; wants lossless audio like Tidal.",
    keyPhrases: ["bitrate", "low", "sound system", "Tidal", "lossless"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },
  {
    text: "Trying to find new artists in a specific genre is impossible. Search just gives me the same 5 popular ones. Where's the deep catalog stuff?",
    title: "Can't discover new artists",
    rating: 2,
    source: "google_play",
    author: "Liam O.",
    daysAgo: 11,
    sentiment: "negative",
    sentimentScore: 0.82,
    theme: "search",
    subTheme: "genre_search_shallow",
    priority: "high",
    priorityReason: "Discovery pain point via search; aligned with project mission.",
    summary: "User cannot find new or deep-catalog artists by genre; only popular results shown.",
    keyPhrases: ["find new artists", "specific genre", "same 5 popular", "deep catalog"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },
  {
    text: "Liked Songs used to be my go-to playlist but now everything I like ends up influencing my recommendations and it's a mess. I want to like a song without it taking over my algorithm.",
    title: "Liking songs breaks recommendations",
    rating: 3,
    source: "google_play",
    author: "Sofia G.",
    daysAgo: 14,
    sentiment: "mixed",
    sentimentScore: 0.62,
    theme: "recommendation_quality",
    subTheme: "liked_songs_pollution",
    priority: "medium",
    priorityReason: "Common complaint; impacts discovery quality for engaged users.",
    summary: "Liking songs over-influences recommendations; user wants decoupled behavior.",
    keyPhrases: ["Liked Songs", "recommendations", "mess", "taking over my algorithm"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },

  // ===== App Store (14) ======================================================
  {
    text: "Discover Weekly is a joke now. Three weeks in a row with the same tracks. I'm a paying customer and you can't even get your flagship feature right.",
    title: "Discover Weekly is a joke",
    rating: 1,
    source: "app_store",
    author: "iUser_88",
    daysAgo: 4,
    sentiment: "negative",
    sentimentScore: 0.93,
    theme: "music_discovery",
    subTheme: "discover_weekly_repetition",
    priority: "high",
    priorityReason: "Premium user, flagship feature broken, public review complaint.",
    summary: "Discover Weekly shows same tracks for three consecutive weeks; Premium user frustrated.",
    keyPhrases: ["Discover Weekly", "same tracks", "three weeks", "flagship feature"],
    isBug: false,
    isFeatureRequest: false,
    isActionable: true,
  },
  {
    text: "Songs skip randomly mid-playback. Happens on WiFi and cellular. iPhone 14 Pro, latest iOS. This is unacceptable for a paid app.",
    title: "Songs skip randomly",
    rating: 1,
    source: "app_store",
    author: "AppleFan_2024",
    daysAgo: 2,
    sentiment: "negative",
    sentimentScore: 0.96,
    theme: "playback_bug",
    subTheme: "playback_skipping",
    priority: "critical",
    priorityReason: "Core playback broken on a flagship device; reproducible across networks.",
    summary: "Songs skip mid-playback on iPhone 14 Pro across WiFi and cellular.",
    keyPhrases: ["skip", "mid-playback", "WiFi and cellular", "iPhone 14 Pro", "iOS"],
    isBug: true,
    isFeatureRequest: false,
    isActionable: true,
  },
  {
    text: "Spotify has no idea what I like. I've been using it for 5 years and it still suggests the same generic pop garbage. Maybe invest in your algorithm instead of podcasts.",
    title: "5 years and still clueless",
    rating: 1,
    source: "app_store",
    author: "musicnerd42",
    daysAgo: 7,
    sentiment: "negative",
    sentimentScore: 0.9,
    theme: "recommendation_quality",
    subTheme: "taste_misunderstanding",
    priority: "high",
    priorityReason: "Long-tenured user at churn risk; algorithm quality issue.",
    summary: "5-year user reports algorithm still suggests generic pop; wants investment in algorithm not podcasts.",
    keyPhrases: ["5 years", "same generic pop", "algorithm", "podcasts"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },
  {
    text: "Bored of the same playlists. Every time I open the app it's the same 'Hot Hits' and 'Today's Top Hits'. I want something curated for me, not what's already popular.",
    title: "Bored of the same playlists",
    rating: 2,
    source: "app_store",
    author: "Emma R.",
    daysAgo: 10,
    sentiment: "negative",
    sentimentScore: 0.8,
    theme: "playlist_fatigue",
    subTheme: "homepage_repetition",
    priority: "medium",
    priorityReason: "Discovery stagnation on home surface; affects engagement.",
    summary: "User bored by repetitive homepage playlists; wants personalized curation.",
    keyPhrases: ["same playlists", "Hot Hits", "Today's Top Hits", "curated for me"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },
  {
    text: "I want a way to explore genres I don't normally listen to. Like, give me a random jazz playlist or some underground hip-hop. Right now you have to dig so deep to find anything new.",
    title: "Make genre exploration easier",
    rating: 3,
    source: "app_store",
    author: "Jordan T.",
    daysAgo: 13,
    sentiment: "mixed",
    sentimentScore: 0.55,
    theme: "music_discovery",
    subTheme: "genre_exploration",
    priority: "high",
    priorityReason: "Discovery feature request aligned with the project mission.",
    summary: "User wants easier genre exploration for unfamiliar music; currently requires deep digging.",
    keyPhrases: ["explore genres", "random jazz", "underground hip-hop", "dig so deep"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },
  {
    text: "Who designed this UI? Everything is buried under menus now. Used to be able to shuffle an album with one tap, now it's three taps and a search. Bring back the old design.",
    title: "UI is a mess",
    rating: 2,
    source: "app_store",
    author: "disappointed_user",
    daysAgo: 18,
    sentiment: "negative",
    sentimentScore: 0.85,
    theme: "ui_ux",
    subTheme: "layout_regression",
    priority: "medium",
    priorityReason: "Usability regression with concrete examples of added friction.",
    summary: "User frustrated by UI changes; simple actions now require multiple taps.",
    keyPhrases: ["UI", "buried under menus", "shuffle", "three taps", "old design"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },
  {
    text: "Search is broken. I'll type in the exact song name and it shows me covers and remixes before the original. Then when I finally find the original, it's greyed out and unplayable. Fix this.",
    title: "Search is broken",
    rating: 1,
    source: "app_store",
    author: "david_w",
    daysAgo: 6,
    sentiment: "negative",
    sentimentScore: 0.91,
    theme: "search",
    subTheme: "search_result_ordering",
    priority: "high",
    priorityReason: "Core search feature broken; affects all users searching for specific tracks.",
    summary: "Search returns covers/remixes before originals; some originals greyed out and unplayable.",
    keyPhrases: ["Search", "exact song name", "covers", "remixes", "greyed out"],
    isBug: true,
    isFeatureRequest: false,
    isActionable: true,
  },
  {
    text: "Found a really cool indie band through a 'Fans Also Like' section last month. That feature is underrated. More of that please.",
    title: "Fans Also Like is great",
    rating: 4,
    source: "app_store",
    author: "ryanp",
    daysAgo: 9,
    sentiment: "positive",
    sentimentScore: 0.82,
    theme: "music_discovery",
    subTheme: "fans_also_like_success",
    priority: "low",
    priorityReason: "Positive feedback; informational. Signals which surfaces drive discovery.",
    summary: "User discovered an indie band via 'Fans Also Like'; wants more such discovery surfaces.",
    keyPhrases: ["Fans Also Like", "indie band", "underrated"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: false,
  },
  {
    text: "Collaborative playlists with my friends are the best feature. We have a road trip playlist that's been going for 3 years. Just wish it was easier to see who added what.",
    title: "Love collaborative playlists",
    rating: 4,
    source: "app_store",
    author: "Rachel K.",
    daysAgo: 16,
    sentiment: "positive",
    sentimentScore: 0.85,
    theme: "social_features",
    subTheme: "collaborative_playlists",
    priority: "low",
    priorityReason: "Positive engagement; minor enhancement request.",
    summary: "User loves collaborative playlists; wants attribution of who added each track.",
    keyPhrases: ["collaborative playlists", "road trip", "who added what"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },
  {
    text: "You paywall everything now. Even basic features are behind Premium. Free tier is unusable with the ads. I get you need to make money but this is greedy.",
    title: "Everything is paywalled",
    rating: 1,
    source: "app_store",
    author: "broke_college_kid",
    daysAgo: 22,
    sentiment: "negative",
    sentimentScore: 0.87,
    theme: "pricing",
    subTheme: "paywall_aggression",
    priority: "medium",
    priorityReason: "Pricing/positioning complaint; common among free-tier users.",
    summary: "User feels too many features are paywalled and free tier is unusable due to ad frequency.",
    keyPhrases: ["paywall", "Premium", "Free tier", "unusable", "ads", "greedy"],
    isBug: false,
    isFeatureRequest: false,
    isActionable: true,
  },
  {
    text: "My Home page is 50% podcasts I'll never listen to. I don't even use podcasts on Spotify. The algorithm should know that by now.",
    title: "Stop pushing podcasts",
    rating: 3,
    source: "app_store",
    author: "alvin_m",
    daysAgo: 11,
    sentiment: "mixed",
    sentimentScore: 0.65,
    theme: "recommendation_quality",
    subTheme: "podcast_over_promotion",
    priority: "medium",
    priorityReason: "Common complaint; impacts home page engagement and perceived relevance.",
    summary: "Home page dominated by podcasts the user never engages with.",
    keyPhrases: ["Home page", "podcasts", "algorithm", "never listen to"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },
  {
    text: "App freezes for 5-10 seconds whenever I switch playlists. Been happening for weeks. Restart doesn't help.",
    title: "Freezes when switching playlists",
    rating: 2,
    source: "app_store",
    author: "nora_b",
    daysAgo: 3,
    sentiment: "negative",
    sentimentScore: 0.88,
    theme: "playback_bug",
    subTheme: "ui_freeze",
    priority: "high",
    priorityReason: "Reproducible performance issue affecting a core navigation flow.",
    summary: "App freezes 5-10 seconds when switching playlists; persists across restarts.",
    keyPhrases: ["freezes", "switch playlists", "5-10 seconds", "Restart doesn't help"],
    isBug: true,
    isFeatureRequest: false,
    isActionable: true,
  },
  {
    text: "Wrapped this year was incredible! Actually showed me artists I forgot I discovered. The whole experience was so fun and shareable.",
    title: "Wrapped was amazing",
    rating: 5,
    source: "app_store",
    author: "katy_s",
    daysAgo: 25,
    sentiment: "positive",
    sentimentScore: 0.92,
    theme: "music_discovery",
    subTheme: "wrapped_experience",
    priority: "low",
    priorityReason: "Positive feedback; informational. Wrapped surfaces prior discoveries.",
    summary: "User delighted by Wrapped; highlights previously forgotten discoveries.",
    keyPhrases: ["Wrapped", "incredible", "artists I forgot", "shareable"],
    isBug: false,
    isFeatureRequest: false,
    isActionable: false,
  },
  {
    text: "I travel internationally a lot for work. Downloads work but I can't browse or discover anything while offline, and when I land my Discover Weekly is stale. Would love a smarter offline mode.",
    title: "Need better offline mode",
    rating: 2,
    source: "app_store",
    author: "global_traveler",
    daysAgo: 17,
    sentiment: "negative",
    sentimentScore: 0.7,
    theme: "offline_mode",
    subTheme: "offline_discovery_gap",
    priority: "medium",
    priorityReason: "Power-user segment gap; aligned with discovery mission.",
    summary: "Frequent international traveler wants smarter offline mode and fresh discovery on reconnect.",
    keyPhrases: ["travel", "offline", "browse", "discover", "Discover Weekly", "stale"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },

  // ===== Reddit (12) =========================================================
  {
    text: "Anyone else feel like Spotify's algorithm is in a rut? Mine just keeps feeding me the same 50 songs no matter what I do. I've tried liking, not liking, skipping, but nothing changes. Is the algorithm broken or is it just me?",
    title: null,
    rating: 1,
    source: "reddit",
    author: "u/deepcuts_only",
    daysAgo: 2,
    sentiment: "negative",
    sentimentScore: 0.85,
    theme: "music_discovery",
    subTheme: "algorithm_rut",
    priority: "high",
    priorityReason: "Community thread validating algorithm stagnation; likely a broad issue.",
    summary: "User reports algorithm stuck on same 50 songs despite varied engagement signals.",
    keyPhrases: ["algorithm", "rut", "same 50 songs", "liking", "skipping", "broken"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },
  {
    text: "Hot take: I miss the old 'Browse' section where you could just pick a genre and dive in. Now everything is so personalized that I never stumble onto anything outside my bubble. Anyone found a workaround?",
    title: "Bring back the Browse section",
    rating: 4,
    source: "reddit",
    author: "u/old_spotify_user",
    daysAgo: 6,
    sentiment: "mixed",
    sentimentScore: 0.5,
    theme: "ui_ux",
    subTheme: "browse_section_removed",
    priority: "high",
    priorityReason: "Strong signal of discovery regression tied to a specific removed UI; community discussion.",
    summary: "User misses genre-browsing Browse section for serendipity; over-personalization traps them in a bubble.",
    keyPhrases: ["Browse", "pick a genre", "personalized", "bubble", "workaround"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },
  {
    text: "PSA: if you let someone else use your Spotify for even a day, your recommendations are RUINED for weeks. My girlfriend played kids' songs for my nephew and now Release Radar is half Cocomelon.",
    title: null,
    rating: 2,
    source: "reddit",
    author: "u/scarred_algorithm",
    daysAgo: 4,
    sentiment: "negative",
    sentimentScore: 0.9,
    theme: "recommendation_quality",
    subTheme: "shared_account_contamination",
    priority: "medium",
    priorityReason: "Common scenario; impacts recommendation trust and discoverability.",
    summary: "Letting someone use account contaminated recommendations with kids' music for weeks.",
    keyPhrases: ["recommendations", "RUINED", "kids' songs", "Cocomelon", "Release Radar"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },
  {
    text: "Unpopular opinion: Discover Weekly hasn't been good since 2019. It used to genuinely surprise me. Now it's just songs I've heard before or adjacent stuff. Am I just too picky?",
    title: "Discover Weekly hasn't been good since 2019",
    rating: 3,
    source: "reddit",
    author: "u/nostalgic_listener",
    daysAgo: 8,
    sentiment: "neutral",
    sentimentScore: 0.4,
    theme: "music_discovery",
    subTheme: "discover_weekly_decline",
    priority: "medium",
    priorityReason: "Sentiment trend on flagship feature; recurring complaint.",
    summary: "User believes Discover Weekly quality has declined since 2019; no longer surprising.",
    keyPhrases: ["Discover Weekly", "2019", "surprise", "adjacent", "too picky"],
    isBug: false,
    isFeatureRequest: false,
    isActionable: true,
  },
  {
    text: "Is anyone else's downloaded music just disappearing? I download a 500-song playlist and two days later half of it needs re-downloading. Drained my data plan twice this month.",
    title: null,
    rating: 1,
    source: "reddit",
    author: "u/mobile_data_victim",
    daysAgo: 3,
    sentiment: "negative",
    sentimentScore: 0.93,
    theme: "playback_bug",
    subTheme: "download_disappearing",
    priority: "critical",
    priorityReason: "Real financial impact (data overage); recurring bug with multiple occurrences reported.",
    summary: "Downloaded playlists partially disappear within days, causing data overage.",
    keyPhrases: ["downloaded music", "disappearing", "500-song playlist", "re-downloading", "data plan"],
    isBug: true,
    isFeatureRequest: false,
    isActionable: true,
  },
  {
    text: "Spotify Social / friend activity feed is honestly my favorite feature. I've discovered so much music just by seeing what my friends are listening to in real time. Please never remove this.",
    title: "Friend activity feed is the best feature",
    rating: 5,
    source: "reddit",
    author: "u/social_listener",
    daysAgo: 12,
    sentiment: "positive",
    sentimentScore: 0.9,
    theme: "social_features",
    subTheme: "friend_activity_feed",
    priority: "low",
    priorityReason: "Positive feedback; opportunity to expand social discovery.",
    summary: "User loves the friend activity feed as a discovery channel; requests it never be removed.",
    keyPhrases: ["Spotify Social", "friend activity", "real time", "discovered"],
    isBug: false,
    isFeatureRequest: false,
    isActionable: false,
  },
  {
    text: "Anyone else's Daily Mixes been the exact same for like a year? I've basically stopped using them. They used to be my favorite feature.",
    title: null,
    rating: 3,
    source: "reddit",
    author: "u/burned_out_on_daily",
    daysAgo: 9,
    sentiment: "mixed",
    sentimentScore: 0.55,
    theme: "playlist_fatigue",
    subTheme: "daily_mix_stale",
    priority: "medium",
    priorityReason: "Recurring complaint; engaged user has abandoned the feature.",
    summary: "User reports Daily Mixes unchanged for a year; has abandoned the feature.",
    keyPhrases: ["Daily Mixes", "same for like a year", "stopped using", "favorite feature"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },
  {
    text: "The library redesign is awful. I can't find ANYTHING. Used to be sorted by artist, now it's some weird 'recently played' mess. Why fix what wasn't broken?",
    title: "Library redesign is awful",
    rating: 2,
    source: "reddit",
    author: "u/bring_back_old_library",
    daysAgo: 14,
    sentiment: "negative",
    sentimentScore: 0.84,
    theme: "ui_ux",
    subTheme: "library_redesign_regression",
    priority: "medium",
    priorityReason: "Usability regression with specific complaint about sort behavior.",
    summary: "User dislikes library redesign; can no longer sort content by artist.",
    keyPhrases: ["library redesign", "can't find", "sorted by artist", "recently played", "wasn't broken"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },
  {
    text: "Search results are wild now. I searched for a specific classical recording and got lo-fi beats and 'study music'. Like what? How is that even close?",
    title: null,
    rating: 2,
    source: "reddit",
    author: "u/classical_fan",
    daysAgo: 7,
    sentiment: "negative",
    sentimentScore: 0.8,
    theme: "search",
    subTheme: "irrelevant_search_results",
    priority: "medium",
    priorityReason: "Search relevance regression with a specific, reproducible example.",
    summary: "Classical music search returns irrelevant lo-fi / study music instead.",
    keyPhrases: ["Search results", "classical recording", "lo-fi beats", "study music"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },
  {
    text: "Unpopular opinion: the 'like' button has ruined Spotify for me. I'm scared to like anything now because it'll dominate my recommendations for months. Bring back the star/heart split or something.",
    title: "The like button has ruined Spotify",
    rating: 3,
    source: "reddit",
    author: "u/afraid_to_like",
    daysAgo: 10,
    sentiment: "mixed",
    sentimentScore: 0.62,
    theme: "recommendation_quality",
    subTheme: "liked_songs_pollution",
    priority: "medium",
    priorityReason: "Common complaint; impacts engagement with a core mechanic.",
    summary: "User avoids liking songs because of recommendation pollution; wants a split like/star control.",
    keyPhrases: ["like button", "ruined", "scared to like", "recommendations", "star/heart"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },
  {
    text: "Spotify Connect has been dropping audio quality randomly for me. Goes from normal to super compressed for no reason. Wired speaker, strong WiFi. Anyone else?",
    title: null,
    rating: 1,
    source: "reddit",
    author: "u/audiophile_pain",
    daysAgo: 6,
    sentiment: "negative",
    sentimentScore: 0.85,
    theme: "audio_quality",
    subTheme: "connect_quality_drop",
    priority: "medium",
    priorityReason: "Reproducible bug with a specific setup; impacts listening experience.",
    summary: "Spotify Connect randomly drops audio quality on a stable wired connection.",
    keyPhrases: ["Spotify Connect", "audio quality", "compressed", "wired speaker", "WiFi"],
    isBug: true,
    isFeatureRequest: false,
    isActionable: true,
  },
  {
    text: "Downloaded playlists randomly switch to 'not downloaded' on my phone. I'll be underground on the subway with no signal and suddenly nothing plays. This has been broken for months.",
    title: "Downloads keep breaking",
    rating: 2,
    source: "reddit",
    author: "u/subway_commuter",
    daysAgo: 5,
    sentiment: "negative",
    sentimentScore: 0.89,
    theme: "offline_mode",
    subTheme: "download_state_flapping",
    priority: "high",
    priorityReason: "Long-standing reproducible bug affecting offline use in real-world conditions.",
    summary: "Downloaded playlists randomly revert to not-downloaded, breaking offline playback on subway.",
    keyPhrases: ["Downloaded playlists", "not downloaded", "subway", "no signal", "broken for months"],
    isBug: true,
    isFeatureRequest: false,
    isActionable: true,
  },

  // ===== Twitter (8) =========================================================
  {
    text: "spotify's algorithm is so lazy at this point, literally just plays the same 5 songs on shuffle no matter how big the playlist is",
    title: null,
    rating: 2,
    source: "twitter",
    author: "@bored_of_spotify",
    daysAgo: 1,
    sentiment: "negative",
    sentimentScore: 0.85,
    theme: "playlist_fatigue",
    subTheme: "shuffle_repetition",
    priority: "medium",
    priorityReason: "Viral-style complaint; reflects common user perception of shuffle bias.",
    summary: "User complains shuffle algorithm repeats the same songs regardless of playlist size.",
    keyPhrases: ["algorithm", "lazy", "same 5 songs", "shuffle", "playlist"],
    isBug: false,
    isFeatureRequest: false,
    isActionable: true,
  },
  {
    text: "day 47 of asking spotify to let me find new artists without them being in my recommended for the next 6 months",
    title: null,
    rating: 1,
    source: "twitter",
    author: "@frustrated_user",
    daysAgo: 2,
    sentiment: "negative",
    sentimentScore: 0.88,
    theme: "recommendation_quality",
    subTheme: "discovery_action_pollution",
    priority: "high",
    priorityReason: "Discovery mission aligned; viral-style complaint, signals product friction.",
    summary: "User frustrated that exploring new artists permanently pollutes recommendations.",
    keyPhrases: ["find new artists", "recommended", "6 months"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },
  {
    text: "liked one (1) jazz song and now spotify thinks i want to hear jazz exclusively forever. the algorithm has zero nuance",
    title: null,
    rating: 2,
    source: "twitter",
    author: "@one_jazz_song",
    daysAgo: 3,
    sentiment: "negative",
    sentimentScore: 0.86,
    theme: "recommendation_quality",
    subTheme: "context_insensitive",
    priority: "high",
    priorityReason: "Common complaint; algorithm quality issue with a clear reproducible trigger.",
    summary: "Single liked jazz song dominates recommendations; algorithm lacks nuance.",
    keyPhrases: ["jazz song", "exclusively forever", "algorithm", "zero nuance"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },
  {
    text: "the free tier ads are out of control. 3 unskippable ads between every song. you're not converting me to premium, you're converting me to apple music",
    title: null,
    rating: 1,
    source: "twitter",
    author: "@ad_free_dreams",
    daysAgo: 4,
    sentiment: "negative",
    sentimentScore: 0.9,
    theme: "pricing",
    subTheme: "ad_frequency",
    priority: "medium",
    priorityReason: "Churn risk to a named competitor; common free-tier sentiment.",
    summary: "Free-tier user threatens churn to Apple Music due to aggressive unskippable ads.",
    keyPhrases: ["free tier", "ads", "unskippable", "Apple Music", "premium"],
    isBug: false,
    isFeatureRequest: false,
    isActionable: true,
  },
  {
    text: "shoutout to whoever makes the 'Fans Also Like' section, found three new artists this week through it. more of that energy please @Spotify",
    title: null,
    rating: 4,
    source: "twitter",
    author: "@happy_listener",
    daysAgo: 5,
    sentiment: "positive",
    sentimentScore: 0.85,
    theme: "music_discovery",
    subTheme: "fans_also_like_success",
    priority: "low",
    priorityReason: "Positive feedback; informational. Signals which surfaces drive discovery.",
    summary: "User found three new artists via 'Fans Also Like'; wants more of that discovery energy.",
    keyPhrases: ["Fans Also Like", "three new artists", "more of that energy"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: false,
  },
  {
    text: "spotify premium and my songs still skip like a scratched cd in 2024. fix your app",
    title: null,
    rating: 1,
    source: "twitter",
    author: "@premium_but_skipping",
    daysAgo: 2,
    sentiment: "negative",
    sentimentScore: 0.92,
    theme: "playback_bug",
    subTheme: "playback_skipping",
    priority: "high",
    priorityReason: "Premium user; public complaint about a core playback failure.",
    summary: "Premium user reports songs skipping like a scratched CD; demands a fix.",
    keyPhrases: ["premium", "songs still skip", "scratched cd", "fix your app"],
    isBug: true,
    isFeatureRequest: false,
    isActionable: true,
  },
  {
    text: "my daily mix has had the exact same songs for 3 months. i could literally predict the next track. boring",
    title: null,
    rating: 2,
    source: "twitter",
    author: "@predictable_mix",
    daysAgo: 6,
    sentiment: "negative",
    sentimentScore: 0.82,
    theme: "playlist_fatigue",
    subTheme: "daily_mix_stale",
    priority: "medium",
    priorityReason: "Recurring theme; engagement risk on a flagship personalization feature.",
    summary: "Daily Mix unchanged for 3 months; user can predict the next track.",
    keyPhrases: ["daily mix", "exact same songs", "3 months", "predict", "boring"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },
  {
    text: "spotify has me in a chokehold of my own taste. i want OUT of my bubble but the algorithm won't let me leave",
    title: null,
    rating: 1,
    source: "twitter",
    author: "@trapped_in_bubble",
    daysAgo: 3,
    sentiment: "negative",
    sentimentScore: 0.87,
    theme: "music_discovery",
    subTheme: "filter_bubble",
    priority: "high",
    priorityReason: "Direct articulation of the core discovery pain point this project targets.",
    summary: "User feels trapped by the algorithm in their own taste bubble; wants escape.",
    keyPhrases: ["chokehold", "my own taste", "bubble", "algorithm", "won't let me leave"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },

  // ===== CSV Upload (2) ======================================================
  {
    text: "Have been a user for 8 years. The recommendation algorithm has noticeably degraded over the past 18 months. Same songs cycling. Considering switching.",
    title: "Long-time user, declining experience",
    rating: 3,
    source: "csv_upload",
    author: "csv_import_4921",
    daysAgo: 30,
    sentiment: "neutral",
    sentimentScore: 0.45,
    theme: "music_discovery",
    subTheme: "algorithm_decline",
    priority: "high",
    priorityReason: "Long-tenured user at churn risk; reports algorithm quality trend.",
    summary: "8-year user reports algorithm degradation over 18 months; considering switching.",
    keyPhrases: ["8 years", "recommendation algorithm", "degraded", "same songs", "switching"],
    isBug: false,
    isFeatureRequest: false,
    isActionable: true,
  },
  {
    text: "I travel a lot for work and need offline access. Downloads work but I can't browse or discover anything offline. Would love an 'offline discovery' playlist that updates when I'm online.",
    title: "Need offline discovery",
    rating: 2,
    source: "csv_upload",
    author: "csv_import_7788",
    daysAgo: 21,
    sentiment: "negative",
    sentimentScore: 0.7,
    theme: "offline_mode",
    subTheme: "offline_discovery_gap",
    priority: "medium",
    priorityReason: "Feature gap from a power-user segment; aligned with the discovery mission.",
    summary: "Frequent traveler wants an offline-friendly discovery playlist that refreshes when online.",
    keyPhrases: ["travel", "offline access", "browse", "discover", "offline discovery"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },
];

// -----------------------------------------------------------------------------
// SEED_COLLECTOR_SOURCES
// -----------------------------------------------------------------------------
// Four default automated collector sources, one per supported source type.
// `config` is a JSON-encoded string (matches the CollectorSource.config column).
// -----------------------------------------------------------------------------

export const SEED_COLLECTOR_SOURCES: SeedCollectorSourceDef[] = [
  {
    sourceType: "google_play",
    name: "Spotify — Google Play Reviews",
    config: JSON.stringify({ appId: "com.spotify.music", lang: "en", sort: "newest" }),
    enabled: true,
    schedule: "0 9 * * *", // daily at 09:00
    lastRunAt: hoursAgo(2),
    lastRunStatus: "success",
    lastRunCount: 24,
    totalCollected: 1840,
  },
  {
    sourceType: "app_store",
    name: "Spotify — App Store Reviews (US)",
    config: JSON.stringify({ appId: "324684580", country: "us" }),
    enabled: true,
    schedule: "30 9 * * *", // daily at 09:30
    lastRunAt: hoursAgo(3),
    lastRunStatus: "success",
    lastRunCount: 18,
    totalCollected: 2105,
  },
  {
    sourceType: "reddit",
    name: "r/spotify — Hot Posts",
    config: JSON.stringify({ subreddit: "spotify", sort: "hot", limit: 100 }),
    enabled: true,
    schedule: "0 */6 * * *", // every 6 hours
    lastRunAt: hoursAgo(1),
    lastRunStatus: "partial",
    lastRunCount: 42,
    totalCollected: 876,
  },
  {
    sourceType: "twitter",
    name: "Spotify Discovery Mentions",
    config: JSON.stringify({
      query: "spotify discovery OR spotify recommendations",
      limit: 100,
    }),
    enabled: true,
    schedule: "0 */4 * * *", // every 4 hours
    lastRunAt: hoursAgo(4),
    lastRunStatus: "success",
    lastRunCount: 67,
    totalCollected: 1245,
  },
];

// -----------------------------------------------------------------------------
// seedDatabase
// -----------------------------------------------------------------------------
// Wipes all existing data (CollectorLog → CollectorSource → Review → Project)
// and inserts one project, all SEED_REVIEWS (with pre-computed AI analysis),
// and the four SEED_COLLECTOR_SOURCES. Returns high-level counts.
//
// The PrismaClient is passed in by the caller (the /api/seed route) — this
// module imports the type only, never instantiates the client itself.
// -----------------------------------------------------------------------------

export async function seedDatabase(db: PrismaClient): Promise<{
  project: any;
  reviewsInserted: number;
  sourcesInserted: number;
}> {
  // 1. Wipe existing data. Order respects FK constraints (though onDelete:
  //    Cascade on Project would handle it, being explicit is safer and clearer).
  await db.collectorLog.deleteMany();
  await db.collectorSource.deleteMany();
  await db.review.deleteMany();
  await db.project.deleteMany();

  // 2. Create the project.
  const project = await db.project.create({
    data: {
      name: "Spotify — Music Discovery",
      description:
        "Growth team initiative: analyze user feedback to increase meaningful music discovery. PM Fellowship graduation project, June 2026.",
    },
  });

  // 3. Insert all seed reviews with pre-computed AI analysis fields.
  const nowMs = Date.now();
  await db.review.createMany({
    data: SEED_REVIEWS.map((r) => ({
      projectId: project.id,
      text: r.text,
      title: r.title,
      rating: r.rating,
      reviewDate: new Date(nowMs - r.daysAgo * MS_PER_DAY),
      source: r.source,
      author: r.author,
      contentHash: createHash("sha256").update(r.text).digest("hex"),
      processed: true,
      analyzedAt: new Date(),
      sentiment: r.sentiment,
      sentimentScore: r.sentimentScore,
      theme: r.theme,
      subTheme: r.subTheme,
      priority: r.priority,
      priorityReason: r.priorityReason,
      summary: r.summary,
      keyPhrases: JSON.stringify(r.keyPhrases),
      isBug: r.isBug,
      isFeatureRequest: r.isFeatureRequest,
      isActionable: r.isActionable,
    })),
  });

  // 4. Insert the four collector sources under the project.
  await db.collectorSource.createMany({
    data: SEED_COLLECTOR_SOURCES.map((s) => ({
      projectId: project.id,
      sourceType: s.sourceType,
      name: s.name,
      config: s.config,
      enabled: s.enabled,
      schedule: s.schedule,
      lastRunAt: s.lastRunAt,
      lastRunStatus: s.lastRunStatus,
      lastRunCount: s.lastRunCount,
      totalCollected: s.totalCollected,
    })),
  });

  return {
    project,
    reviewsInserted: SEED_REVIEWS.length,
    sourcesInserted: SEED_COLLECTOR_SOURCES.length,
  };
}
