// =============================================================================
// ReviewPulse — Seed Data
// =============================================================================
// Realistic seed data for the ReviewPulse demo: ~105 user reviews about a
// Spotify-like music streaming app, with a heavy focus on MUSIC DISCOVERY
// pain points (the project's core mission). Each review ships with pre-computed
// AI analysis fields so the dashboard renders rich data on first load without
// needing to run the AI processor.
//
// Exports:
//   - SeedReviewDef                 — shape of one seed review
//   - SEED_REVIEWS                  — 105 hand-written reviews (50 original + 55 added in Task r4)
//   - SeedCollectorSourceDef        — shape of one seed collector source
//   - SEED_COLLECTOR_SOURCES        — 4 default collector sources (one per type)
//   - seedDatabase(db)              — wipes DB and inserts 1 project + reviews + sources
//
// Importing this module has NO side effects. Only calling `seedDatabase(db)`
// writes to the database.
//
// Review distribution (105 total = 50 original + 55 added in Task r4; remapped to the
//   11-category theme taxonomy in Task i9):
//   Sources:     google_play 32 · app_store 29 · reddit 24 · twitter 18 · csv_upload 2
//   Themes:      content 64 · usability 11 · reliability 10 · performance 7 ·
//                pricing 7 · features 6   (onboarding/payment/support/security/other = 0)
//   Ratings:     1★ 29 · 2★ 39 · 3★ 17 · 4★ 12 · 5★ 8   (skewed negative — pain-point project)
//   Sentiments:  negative 68 · mixed 14 · positive 18 · neutral 5
//
// Legacy → new theme mapping applied in Task i9:
//   music_discovery / recommendation_quality / playlist_fatigue / audio_quality → content
//   ui_ux / search → usability
//   offline_mode → reliability
//   social_features → features
//   pricing → pricing (unchanged)
//   playback_bug → split: performance (crashes/skips/freezes) vs reliability (offline/crossfade/connect failures)
// =============================================================================

import { createHash } from "crypto";
import type { PrismaClient } from "@prisma/client";

// -----------------------------------------------------------------------------
// Types
// -----------------------------------------------------------------------------

export interface SeedReviewDef {
  text: string;
  title: string | null;
  rating: number; // 1-5
  source: "google_play" | "app_store" | "reddit" | "twitter" | "csv_upload";
  author: string;
  daysAgo: number; // how many days ago the review was posted
  // Pre-computed AI analysis fields:
  sentiment: "positive" | "negative" | "neutral" | "mixed";
  sentimentScore: number; // 0-1
  theme: string; // snake_case
  subTheme: string;
  priority: "critical" | "high" | "medium" | "low";
  priorityReason: string;
  summary: string;
  keyPhrases: string[];
  isBug: boolean;
  isFeatureRequest: boolean;
  isActionable: boolean;
}

export interface SeedCollectorSourceDef {
  sourceType: "google_play" | "app_store" | "reddit" | "twitter";
  name: string;
  config: string; // JSON-encoded config
  enabled: boolean;
  schedule: string; // cron
  lastRunAt: Date;
  lastRunStatus: "success" | "partial" | "failed";
  lastRunCount: number;
  totalCollected: number;
}

const MS_PER_DAY = 86_400_000;
const MS_PER_HOUR = 3_600_000;
const now = Date.now();
const hoursAgo = (h: number) => new Date(now - h * MS_PER_HOUR);

// -----------------------------------------------------------------------------
// SEED_REVIEWS
// -----------------------------------------------------------------------------
// 105 realistic reviews grouped by source. The first 50 (original) are grouped
// by source; the remaining 55 (added in Task r4) are appended under the
// "Expansion (r4)" section, also grouped by source. Authors are plausible
// usernames; titles are short and realistic (Play Store / App Store always have
// titles; Reddit posts have titles / Reddit comments and Twitter posts use null).
// -----------------------------------------------------------------------------

export const SEED_REVIEWS: SeedReviewDef[] = [
  // ===== Google Play (14) ====================================================
  {
    text: "Discover Weekly used to be the best part of Spotify but now it just recycles the same 30 songs every week. I've heard all of them already. Why even bother? Fix this.",
    title: "Discover Weekly is broken",
    rating: 1,
    source: "google_play",
    author: "Marcus T.",
    daysAgo: 3,
    sentiment: "negative",
    sentimentScore: 0.92,
    theme: "content",
    subTheme: "discover_weekly_repetition",
    priority: "high",
    priorityReason: "Flagship discovery feature failing for engaged user; recurring complaint pattern across sources.",
    summary: "Discover Weekly recycles the same 30 songs weekly; user feels the feature is broken.",
    keyPhrases: ["Discover Weekly", "recycles", "same 30 songs", "every week"],
    isBug: false,
    isFeatureRequest: false,
    isActionable: true,
  },
  {
    text: "I feel like I'm stuck in a bubble. The algorithm just feeds me variations of what I already listen to. I want to actually discover new artists, not more of the same.",
    title: "Stuck in a music bubble",
    rating: 2,
    source: "google_play",
    author: "Priya K.",
    daysAgo: 5,
    sentiment: "negative",
    sentimentScore: 0.85,
    theme: "content",
    subTheme: "filter_bubble",
    priority: "high",
    priorityReason: "Direct articulation of the core discovery pain point this project targets.",
    summary: "User feels trapped in a recommendation bubble; wants genuine new-artist discovery.",
    keyPhrases: ["stuck in a bubble", "algorithm", "discover new artists", "more of the same"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },
  {
    text: "I love that Spotify has genre playlists but finding them is a pain. Once you stumble onto a good niche like lo-fi jazz or indie folk, it's great. Just wish it was easier to find new genres in the first place.",
    title: "Great when you find niches",
    rating: 4,
    source: "google_play",
    author: "Derek L.",
    daysAgo: 8,
    sentiment: "mixed",
    sentimentScore: 0.55,
    theme: "content",
    subTheme: "genre_exploration",
    priority: "medium",
    priorityReason: "Positive engagement with a clear discoverability improvement opportunity.",
    summary: "User enjoys niche genre playlists once found but finds discovering new genres difficult.",
    keyPhrases: ["genre playlists", "lo-fi jazz", "indie folk", "find new genres"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },
  {
    text: "App crashes every time I open it on my Galaxy S22. Reinstalled twice, cleared cache, nothing works. Used to love this app, now I can't even use it.",
    title: "Crashes on launch",
    rating: 1,
    source: "google_play",
    author: "Brittany M.",
    daysAgo: 1,
    sentiment: "negative",
    sentimentScore: 0.95,
    theme: "performance",
    subTheme: "launch_crash",
    priority: "critical",
    priorityReason: "Complete app failure on a common device model despite reinstall/cache clear.",
    summary: "App crashes on launch on Galaxy S22 despite reinstall and cache clear.",
    keyPhrases: ["crashes", "Galaxy S22", "reinstalled", "cleared cache"],
    isBug: true,
    isFeatureRequest: false,
    isActionable: true,
  },
  {
    text: "Premium went up again and now there's ads in podcasts too? You're pushing me to Apple Music. The free tier is also basically unusable with the ad frequency now.",
    title: "Pricing keeps climbing",
    rating: 2,
    source: "google_play",
    author: "Tomás R.",
    daysAgo: 12,
    sentiment: "negative",
    sentimentScore: 0.88,
    theme: "pricing",
    subTheme: "price_increase",
    priority: "medium",
    priorityReason: "Pricing churn risk; user explicitly names a competitor alternative.",
    summary: "User frustrated by Premium price hikes and podcast ads; considering Apple Music.",
    keyPhrases: ["Premium went up", "ads in podcasts", "Apple Music", "free tier"],
    isBug: false,
    isFeatureRequest: false,
    isActionable: true,
  },
  {
    text: "Remember when Spotify actually showed you random cool stuff? Now everything is so calculated. I miss the serendipity. Give me a 'surprise me' button or something.",
    title: "Where's the serendipity?",
    rating: 2,
    source: "google_play",
    author: "Hannah W.",
    daysAgo: 6,
    sentiment: "negative",
    sentimentScore: 0.8,
    theme: "content",
    subTheme: "lack_of_serendipity",
    priority: "medium",
    priorityReason: "Feature gap request directly aligned with the discovery mission.",
    summary: "User misses serendipitous discovery; wants a 'surprise me' feature.",
    keyPhrases: ["serendipity", "calculated", "surprise me", "random cool stuff"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },
  {
    text: "I liked ONE classical piece and now my recommendations are flooded with classical music. The algorithm doesn't understand context. Annoying.",
    title: "One song ruined my recommendations",
    rating: 2,
    source: "google_play",
    author: "Oliver B.",
    daysAgo: 9,
    sentiment: "negative",
    sentimentScore: 0.83,
    theme: "content",
    subTheme: "context_insensitive",
    priority: "high",
    priorityReason: "Algorithm quality complaint; likely affects many users with diverse taste.",
    summary: "Single liked classical song floods recommendations; algorithm lacks context.",
    keyPhrases: ["classical piece", "flooded", "algorithm doesn't understand", "context"],
    isBug: false,
    isFeatureRequest: false,
    isActionable: true,
  },
  {
    text: "Daily Mix 1-6 have been basically the same for 6 months. Same songs, same order. They were great at first. Now they're just background noise.",
    title: "Daily Mix needs refresh",
    rating: 3,
    source: "google_play",
    author: "Jasmine P.",
    daysAgo: 4,
    sentiment: "mixed",
    sentimentScore: 0.6,
    theme: "content",
    subTheme: "daily_mix_stale",
    priority: "medium",
    priorityReason: "Engaged user reporting staleness on a flagship personalization feature.",
    summary: "Daily Mixes have remained static for 6 months; user finds them stale.",
    keyPhrases: ["Daily Mix", "same for 6 months", "background noise", "stale"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },
  {
    text: "Downloaded playlists for my flight and they wouldn't play offline. Just sat there loading forever. This is the third time this has happened. I pay for Premium specifically for this feature.",
    title: "Offline downloads don't work",
    rating: 1,
    source: "google_play",
    author: "Kenji S.",
    daysAgo: 2,
    sentiment: "negative",
    sentimentScore: 0.94,
    theme: "reliability",
    subTheme: "offline_playback_failure",
    priority: "critical",
    priorityReason: "Premium feature failure; reproducible across multiple attempts.",
    summary: "Downloaded playlists fail to play offline; recurring issue for Premium subscriber.",
    keyPhrases: ["Downloaded playlists", "flight", "offline", "loading forever", "Premium"],
    isBug: true,
    isFeatureRequest: false,
    isActionable: true,
  },
  {
    text: "The new UI is confusing. Library is hidden, I can't find my playlists easily, and the home screen is cluttered with podcasts I don't care about. Please simplify.",
    title: "UI getting worse",
    rating: 3,
    source: "google_play",
    author: "Frank D.",
    daysAgo: 15,
    sentiment: "neutral",
    sentimentScore: 0.45,
    theme: "usability",
    subTheme: "navigation_confusion",
    priority: "medium",
    priorityReason: "Usability regression with multiple specific complaints.",
    summary: "User finds new UI confusing; library hidden and home cluttered with podcasts.",
    keyPhrases: ["new UI", "Library is hidden", "cluttered", "podcasts", "simplify"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },
  {
    text: "I actually found an amazing indie artist through Release Radar last week and now I'm obsessed. When Spotify works, it really works. Just wish this happened more often!",
    title: "Release Radar delivered",
    rating: 5,
    source: "google_play",
    author: "Aisha N.",
    daysAgo: 7,
    sentiment: "positive",
    sentimentScore: 0.88,
    theme: "content",
    subTheme: "release_radar_success",
    priority: "low",
    priorityReason: "Positive feedback; informational only.",
    summary: "User discovered a new indie artist via Release Radar; wishes for more frequent success.",
    keyPhrases: ["Release Radar", "indie artist", "obsessed", "works"],
    isBug: false,
    isFeatureRequest: false,
    isActionable: false,
  },
  {
    text: "Why is the max bitrate still so low? On a good sound system you can really tell. Tidal sounds way better for the same price. Please add lossless already.",
    title: "Where's lossless?",
    rating: 2,
    source: "google_play",
    author: "Marcus H.",
    daysAgo: 20,
    sentiment: "negative",
    sentimentScore: 0.78,
    theme: "content",
    subTheme: "low_bitrate",
    priority: "low",
    priorityReason: "Long-standing request; competitive gap, not core to the discovery mission.",
    summary: "User complains about low max bitrate; wants lossless audio like Tidal.",
    keyPhrases: ["bitrate", "low", "sound system", "Tidal", "lossless"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },
  {
    text: "Trying to find new artists in a specific genre is impossible. Search just gives me the same 5 popular ones. Where's the deep catalog stuff?",
    title: "Can't discover new artists",
    rating: 2,
    source: "google_play",
    author: "Liam O.",
    daysAgo: 11,
    sentiment: "negative",
    sentimentScore: 0.82,
    theme: "usability",
    subTheme: "genre_search_shallow",
    priority: "high",
    priorityReason: "Discovery pain point via search; aligned with project mission.",
    summary: "User cannot find new or deep-catalog artists by genre; only popular results shown.",
    keyPhrases: ["find new artists", "specific genre", "same 5 popular", "deep catalog"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },
  {
    text: "Liked Songs used to be my go-to playlist but now everything I like ends up influencing my recommendations and it's a mess. I want to like a song without it taking over my algorithm.",
    title: "Liking songs breaks recommendations",
    rating: 3,
    source: "google_play",
    author: "Sofia G.",
    daysAgo: 14,
    sentiment: "mixed",
    sentimentScore: 0.62,
    theme: "content",
    subTheme: "liked_songs_pollution",
    priority: "medium",
    priorityReason: "Common complaint; impacts discovery quality for engaged users.",
    summary: "Liking songs over-influences recommendations; user wants decoupled behavior.",
    keyPhrases: ["Liked Songs", "recommendations", "mess", "taking over my algorithm"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },

  // ===== App Store (14) ======================================================
  {
    text: "Discover Weekly is a joke now. Three weeks in a row with the same tracks. I'm a paying customer and you can't even get your flagship feature right.",
    title: "Discover Weekly is a joke",
    rating: 1,
    source: "app_store",
    author: "iUser_88",
    daysAgo: 4,
    sentiment: "negative",
    sentimentScore: 0.93,
    theme: "content",
    subTheme: "discover_weekly_repetition",
    priority: "high",
    priorityReason: "Premium user, flagship feature broken, public review complaint.",
    summary: "Discover Weekly shows same tracks for three consecutive weeks; Premium user frustrated.",
    keyPhrases: ["Discover Weekly", "same tracks", "three weeks", "flagship feature"],
    isBug: false,
    isFeatureRequest: false,
    isActionable: true,
  },
  {
    text: "Songs skip randomly mid-playback. Happens on WiFi and cellular. iPhone 14 Pro, latest iOS. This is unacceptable for a paid app.",
    title: "Songs skip randomly",
    rating: 1,
    source: "app_store",
    author: "AppleFan_2024",
    daysAgo: 2,
    sentiment: "negative",
    sentimentScore: 0.96,
    theme: "performance",
    subTheme: "playback_skipping",
    priority: "critical",
    priorityReason: "Core playback broken on a flagship device; reproducible across networks.",
    summary: "Songs skip mid-playback on iPhone 14 Pro across WiFi and cellular.",
    keyPhrases: ["skip", "mid-playback", "WiFi and cellular", "iPhone 14 Pro", "iOS"],
    isBug: true,
    isFeatureRequest: false,
    isActionable: true,
  },
  {
    text: "Spotify has no idea what I like. I've been using it for 5 years and it still suggests the same generic pop garbage. Maybe invest in your algorithm instead of podcasts.",
    title: "5 years and still clueless",
    rating: 1,
    source: "app_store",
    author: "musicnerd42",
    daysAgo: 7,
    sentiment: "negative",
    sentimentScore: 0.9,
    theme: "content",
    subTheme: "taste_misunderstanding",
    priority: "high",
    priorityReason: "Long-tenured user at churn risk; algorithm quality issue.",
    summary: "5-year user reports algorithm still suggests generic pop; wants investment in algorithm not podcasts.",
    keyPhrases: ["5 years", "same generic pop", "algorithm", "podcasts"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },
  {
    text: "Bored of the same playlists. Every time I open the app it's the same 'Hot Hits' and 'Today's Top Hits'. I want something curated for me, not what's already popular.",
    title: "Bored of the same playlists",
    rating: 2,
    source: "app_store",
    author: "Emma R.",
    daysAgo: 10,
    sentiment: "negative",
    sentimentScore: 0.8,
    theme: "content",
    subTheme: "homepage_repetition",
    priority: "medium",
    priorityReason: "Discovery stagnation on home surface; affects engagement.",
    summary: "User bored by repetitive homepage playlists; wants personalized curation.",
    keyPhrases: ["same playlists", "Hot Hits", "Today's Top Hits", "curated for me"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },
  {
    text: "I want a way to explore genres I don't normally listen to. Like, give me a random jazz playlist or some underground hip-hop. Right now you have to dig so deep to find anything new.",
    title: "Make genre exploration easier",
    rating: 3,
    source: "app_store",
    author: "Jordan T.",
    daysAgo: 13,
    sentiment: "mixed",
    sentimentScore: 0.55,
    theme: "content",
    subTheme: "genre_exploration",
    priority: "high",
    priorityReason: "Discovery feature request aligned with the project mission.",
    summary: "User wants easier genre exploration for unfamiliar music; currently requires deep digging.",
    keyPhrases: ["explore genres", "random jazz", "underground hip-hop", "dig so deep"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },
  {
    text: "Who designed this UI? Everything is buried under menus now. Used to be able to shuffle an album with one tap, now it's three taps and a search. Bring back the old design.",
    title: "UI is a mess",
    rating: 2,
    source: "app_store",
    author: "disappointed_user",
    daysAgo: 18,
    sentiment: "negative",
    sentimentScore: 0.85,
    theme: "usability",
    subTheme: "layout_regression",
    priority: "medium",
    priorityReason: "Usability regression with concrete examples of added friction.",
    summary: "User frustrated by UI changes; simple actions now require multiple taps.",
    keyPhrases: ["UI", "buried under menus", "shuffle", "three taps", "old design"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },
  {
    text: "Search is broken. I'll type in the exact song name and it shows me covers and remixes before the original. Then when I finally find the original, it's greyed out and unplayable. Fix this.",
    title: "Search is broken",
    rating: 1,
    source: "app_store",
    author: "david_w",
    daysAgo: 6,
    sentiment: "negative",
    sentimentScore: 0.91,
    theme: "usability",
    subTheme: "search_result_ordering",
    priority: "high",
    priorityReason: "Core search feature broken; affects all users searching for specific tracks.",
    summary: "Search returns covers/remixes before originals; some originals greyed out and unplayable.",
    keyPhrases: ["Search", "exact song name", "covers", "remixes", "greyed out"],
    isBug: true,
    isFeatureRequest: false,
    isActionable: true,
  },
  {
    text: "Found a really cool indie band through a 'Fans Also Like' section last month. That feature is underrated. More of that please.",
    title: "Fans Also Like is great",
    rating: 4,
    source: "app_store",
    author: "ryanp",
    daysAgo: 9,
    sentiment: "positive",
    sentimentScore: 0.82,
    theme: "content",
    subTheme: "fans_also_like_success",
    priority: "low",
    priorityReason: "Positive feedback; informational. Signals which surfaces drive discovery.",
    summary: "User discovered an indie band via 'Fans Also Like'; wants more such discovery surfaces.",
    keyPhrases: ["Fans Also Like", "indie band", "underrated"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: false,
  },
  {
    text: "Collaborative playlists with my friends are the best feature. We have a road trip playlist that's been going for 3 years. Just wish it was easier to see who added what.",
    title: "Love collaborative playlists",
    rating: 4,
    source: "app_store",
    author: "Rachel K.",
    daysAgo: 16,
    sentiment: "positive",
    sentimentScore: 0.85,
    theme: "features",
    subTheme: "collaborative_playlists",
    priority: "low",
    priorityReason: "Positive engagement; minor enhancement request.",
    summary: "User loves collaborative playlists; wants attribution of who added each track.",
    keyPhrases: ["collaborative playlists", "road trip", "who added what"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },
  {
    text: "You paywall everything now. Even basic features are behind Premium. Free tier is unusable with the ads. I get you need to make money but this is greedy.",
    title: "Everything is paywalled",
    rating: 1,
    source: "app_store",
    author: "broke_college_kid",
    daysAgo: 22,
    sentiment: "negative",
    sentimentScore: 0.87,
    theme: "pricing",
    subTheme: "paywall_aggression",
    priority: "medium",
    priorityReason: "Pricing/positioning complaint; common among free-tier users.",
    summary: "User feels too many features are paywalled and free tier is unusable due to ad frequency.",
    keyPhrases: ["paywall", "Premium", "Free tier", "unusable", "ads", "greedy"],
    isBug: false,
    isFeatureRequest: false,
    isActionable: true,
  },
  {
    text: "My Home page is 50% podcasts I'll never listen to. I don't even use podcasts on Spotify. The algorithm should know that by now.",
    title: "Stop pushing podcasts",
    rating: 3,
    source: "app_store",
    author: "alvin_m",
    daysAgo: 11,
    sentiment: "mixed",
    sentimentScore: 0.65,
    theme: "content",
    subTheme: "podcast_over_promotion",
    priority: "medium",
    priorityReason: "Common complaint; impacts home page engagement and perceived relevance.",
    summary: "Home page dominated by podcasts the user never engages with.",
    keyPhrases: ["Home page", "podcasts", "algorithm", "never listen to"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },
  {
    text: "App freezes for 5-10 seconds whenever I switch playlists. Been happening for weeks. Restart doesn't help.",
    title: "Freezes when switching playlists",
    rating: 2,
    source: "app_store",
    author: "nora_b",
    daysAgo: 3,
    sentiment: "negative",
    sentimentScore: 0.88,
    theme: "performance",
    subTheme: "ui_freeze",
    priority: "high",
    priorityReason: "Reproducible performance issue affecting a core navigation flow.",
    summary: "App freezes 5-10 seconds when switching playlists; persists across restarts.",
    keyPhrases: ["freezes", "switch playlists", "5-10 seconds", "Restart doesn't help"],
    isBug: true,
    isFeatureRequest: false,
    isActionable: true,
  },
  {
    text: "Wrapped this year was incredible! Actually showed me artists I forgot I discovered. The whole experience was so fun and shareable.",
    title: "Wrapped was amazing",
    rating: 5,
    source: "app_store",
    author: "katy_s",
    daysAgo: 25,
    sentiment: "positive",
    sentimentScore: 0.92,
    theme: "content",
    subTheme: "wrapped_experience",
    priority: "low",
    priorityReason: "Positive feedback; informational. Wrapped surfaces prior discoveries.",
    summary: "User delighted by Wrapped; highlights previously forgotten discoveries.",
    keyPhrases: ["Wrapped", "incredible", "artists I forgot", "shareable"],
    isBug: false,
    isFeatureRequest: false,
    isActionable: false,
  },
  {
    text: "I travel internationally a lot for work. Downloads work but I can't browse or discover anything while offline, and when I land my Discover Weekly is stale. Would love a smarter offline mode.",
    title: "Need better offline mode",
    rating: 2,
    source: "app_store",
    author: "global_traveler",
    daysAgo: 17,
    sentiment: "negative",
    sentimentScore: 0.7,
    theme: "reliability",
    subTheme: "offline_discovery_gap",
    priority: "medium",
    priorityReason: "Power-user segment gap; aligned with discovery mission.",
    summary: "Frequent international traveler wants smarter offline mode and fresh discovery on reconnect.",
    keyPhrases: ["travel", "offline", "browse", "discover", "Discover Weekly", "stale"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },

  // ===== Reddit (12) =========================================================
  {
    text: "Anyone else feel like Spotify's algorithm is in a rut? Mine just keeps feeding me the same 50 songs no matter what I do. I've tried liking, not liking, skipping, but nothing changes. Is the algorithm broken or is it just me?",
    title: null,
    rating: 1,
    source: "reddit",
    author: "u/deepcuts_only",
    daysAgo: 2,
    sentiment: "negative",
    sentimentScore: 0.85,
    theme: "content",
    subTheme: "algorithm_rut",
    priority: "high",
    priorityReason: "Community thread validating algorithm stagnation; likely a broad issue.",
    summary: "User reports algorithm stuck on same 50 songs despite varied engagement signals.",
    keyPhrases: ["algorithm", "rut", "same 50 songs", "liking", "skipping", "broken"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },
  {
    text: "Hot take: I miss the old 'Browse' section where you could just pick a genre and dive in. Now everything is so personalized that I never stumble onto anything outside my bubble. Anyone found a workaround?",
    title: "Bring back the Browse section",
    rating: 4,
    source: "reddit",
    author: "u/old_spotify_user",
    daysAgo: 6,
    sentiment: "mixed",
    sentimentScore: 0.5,
    theme: "usability",
    subTheme: "browse_section_removed",
    priority: "high",
    priorityReason: "Strong signal of discovery regression tied to a specific removed UI; community discussion.",
    summary: "User misses genre-browsing Browse section for serendipity; over-personalization traps them in a bubble.",
    keyPhrases: ["Browse", "pick a genre", "personalized", "bubble", "workaround"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },
  {
    text: "PSA: if you let someone else use your Spotify for even a day, your recommendations are RUINED for weeks. My girlfriend played kids' songs for my nephew and now Release Radar is half Cocomelon.",
    title: null,
    rating: 2,
    source: "reddit",
    author: "u/scarred_algorithm",
    daysAgo: 4,
    sentiment: "negative",
    sentimentScore: 0.9,
    theme: "content",
    subTheme: "shared_account_contamination",
    priority: "medium",
    priorityReason: "Common scenario; impacts recommendation trust and discoverability.",
    summary: "Letting someone use account contaminated recommendations with kids' music for weeks.",
    keyPhrases: ["recommendations", "RUINED", "kids' songs", "Cocomelon", "Release Radar"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },
  {
    text: "Unpopular opinion: Discover Weekly hasn't been good since 2019. It used to genuinely surprise me. Now it's just songs I've heard before or adjacent stuff. Am I just too picky?",
    title: "Discover Weekly hasn't been good since 2019",
    rating: 3,
    source: "reddit",
    author: "u/nostalgic_listener",
    daysAgo: 8,
    sentiment: "neutral",
    sentimentScore: 0.4,
    theme: "content",
    subTheme: "discover_weekly_decline",
    priority: "medium",
    priorityReason: "Sentiment trend on flagship feature; recurring complaint.",
    summary: "User believes Discover Weekly quality has declined since 2019; no longer surprising.",
    keyPhrases: ["Discover Weekly", "2019", "surprise", "adjacent", "too picky"],
    isBug: false,
    isFeatureRequest: false,
    isActionable: true,
  },
  {
    text: "Is anyone else's downloaded music just disappearing? I download a 500-song playlist and two days later half of it needs re-downloading. Drained my data plan twice this month.",
    title: null,
    rating: 1,
    source: "reddit",
    author: "u/mobile_data_victim",
    daysAgo: 3,
    sentiment: "negative",
    sentimentScore: 0.93,
    theme: "reliability",
    subTheme: "download_disappearing",
    priority: "critical",
    priorityReason: "Real financial impact (data overage); recurring bug with multiple occurrences reported.",
    summary: "Downloaded playlists partially disappear within days, causing data overage.",
    keyPhrases: ["downloaded music", "disappearing", "500-song playlist", "re-downloading", "data plan"],
    isBug: true,
    isFeatureRequest: false,
    isActionable: true,
  },
  {
    text: "Spotify Social / friend activity feed is honestly my favorite feature. I've discovered so much music just by seeing what my friends are listening to in real time. Please never remove this.",
    title: "Friend activity feed is the best feature",
    rating: 5,
    source: "reddit",
    author: "u/social_listener",
    daysAgo: 12,
    sentiment: "positive",
    sentimentScore: 0.9,
    theme: "features",
    subTheme: "friend_activity_feed",
    priority: "low",
    priorityReason: "Positive feedback; opportunity to expand social discovery.",
    summary: "User loves the friend activity feed as a discovery channel; requests it never be removed.",
    keyPhrases: ["Spotify Social", "friend activity", "real time", "discovered"],
    isBug: false,
    isFeatureRequest: false,
    isActionable: false,
  },
  {
    text: "Anyone else's Daily Mixes been the exact same for like a year? I've basically stopped using them. They used to be my favorite feature.",
    title: null,
    rating: 3,
    source: "reddit",
    author: "u/burned_out_on_daily",
    daysAgo: 9,
    sentiment: "mixed",
    sentimentScore: 0.55,
    theme: "content",
    subTheme: "daily_mix_stale",
    priority: "medium",
    priorityReason: "Recurring complaint; engaged user has abandoned the feature.",
    summary: "User reports Daily Mixes unchanged for a year; has abandoned the feature.",
    keyPhrases: ["Daily Mixes", "same for like a year", "stopped using", "favorite feature"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },
  {
    text: "The library redesign is awful. I can't find ANYTHING. Used to be sorted by artist, now it's some weird 'recently played' mess. Why fix what wasn't broken?",
    title: "Library redesign is awful",
    rating: 2,
    source: "reddit",
    author: "u/bring_back_old_library",
    daysAgo: 14,
    sentiment: "negative",
    sentimentScore: 0.84,
    theme: "usability",
    subTheme: "library_redesign_regression",
    priority: "medium",
    priorityReason: "Usability regression with specific complaint about sort behavior.",
    summary: "User dislikes library redesign; can no longer sort content by artist.",
    keyPhrases: ["library redesign", "can't find", "sorted by artist", "recently played", "wasn't broken"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },
  {
    text: "Search results are wild now. I searched for a specific classical recording and got lo-fi beats and 'study music'. Like what? How is that even close?",
    title: null,
    rating: 2,
    source: "reddit",
    author: "u/classical_fan",
    daysAgo: 7,
    sentiment: "negative",
    sentimentScore: 0.8,
    theme: "usability",
    subTheme: "irrelevant_search_results",
    priority: "medium",
    priorityReason: "Search relevance regression with a specific, reproducible example.",
    summary: "Classical music search returns irrelevant lo-fi / study music instead.",
    keyPhrases: ["Search results", "classical recording", "lo-fi beats", "study music"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },
  {
    text: "Unpopular opinion: the 'like' button has ruined Spotify for me. I'm scared to like anything now because it'll dominate my recommendations for months. Bring back the star/heart split or something.",
    title: "The like button has ruined Spotify",
    rating: 3,
    source: "reddit",
    author: "u/afraid_to_like",
    daysAgo: 10,
    sentiment: "mixed",
    sentimentScore: 0.62,
    theme: "content",
    subTheme: "liked_songs_pollution",
    priority: "medium",
    priorityReason: "Common complaint; impacts engagement with a core mechanic.",
    summary: "User avoids liking songs because of recommendation pollution; wants a split like/star control.",
    keyPhrases: ["like button", "ruined", "scared to like", "recommendations", "star/heart"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },
  {
    text: "Spotify Connect has been dropping audio quality randomly for me. Goes from normal to super compressed for no reason. Wired speaker, strong WiFi. Anyone else?",
    title: null,
    rating: 1,
    source: "reddit",
    author: "u/audiophile_pain",
    daysAgo: 6,
    sentiment: "negative",
    sentimentScore: 0.85,
    theme: "content",
    subTheme: "connect_quality_drop",
    priority: "medium",
    priorityReason: "Reproducible bug with a specific setup; impacts listening experience.",
    summary: "Spotify Connect randomly drops audio quality on a stable wired connection.",
    keyPhrases: ["Spotify Connect", "audio quality", "compressed", "wired speaker", "WiFi"],
    isBug: true,
    isFeatureRequest: false,
    isActionable: true,
  },
  {
    text: "Downloaded playlists randomly switch to 'not downloaded' on my phone. I'll be underground on the subway with no signal and suddenly nothing plays. This has been broken for months.",
    title: "Downloads keep breaking",
    rating: 2,
    source: "reddit",
    author: "u/subway_commuter",
    daysAgo: 5,
    sentiment: "negative",
    sentimentScore: 0.89,
    theme: "reliability",
    subTheme: "download_state_flapping",
    priority: "high",
    priorityReason: "Long-standing reproducible bug affecting offline use in real-world conditions.",
    summary: "Downloaded playlists randomly revert to not-downloaded, breaking offline playback on subway.",
    keyPhrases: ["Downloaded playlists", "not downloaded", "subway", "no signal", "broken for months"],
    isBug: true,
    isFeatureRequest: false,
    isActionable: true,
  },

  // ===== Twitter (8) =========================================================
  {
    text: "spotify's algorithm is so lazy at this point, literally just plays the same 5 songs on shuffle no matter how big the playlist is",
    title: null,
    rating: 2,
    source: "twitter",
    author: "@bored_of_spotify",
    daysAgo: 1,
    sentiment: "negative",
    sentimentScore: 0.85,
    theme: "content",
    subTheme: "shuffle_repetition",
    priority: "medium",
    priorityReason: "Viral-style complaint; reflects common user perception of shuffle bias.",
    summary: "User complains shuffle algorithm repeats the same songs regardless of playlist size.",
    keyPhrases: ["algorithm", "lazy", "same 5 songs", "shuffle", "playlist"],
    isBug: false,
    isFeatureRequest: false,
    isActionable: true,
  },
  {
    text: "day 47 of asking spotify to let me find new artists without them being in my recommended for the next 6 months",
    title: null,
    rating: 1,
    source: "twitter",
    author: "@frustrated_user",
    daysAgo: 2,
    sentiment: "negative",
    sentimentScore: 0.88,
    theme: "content",
    subTheme: "discovery_action_pollution",
    priority: "high",
    priorityReason: "Discovery mission aligned; viral-style complaint, signals product friction.",
    summary: "User frustrated that exploring new artists permanently pollutes recommendations.",
    keyPhrases: ["find new artists", "recommended", "6 months"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },
  {
    text: "liked one (1) jazz song and now spotify thinks i want to hear jazz exclusively forever. the algorithm has zero nuance",
    title: null,
    rating: 2,
    source: "twitter",
    author: "@one_jazz_song",
    daysAgo: 3,
    sentiment: "negative",
    sentimentScore: 0.86,
    theme: "content",
    subTheme: "context_insensitive",
    priority: "high",
    priorityReason: "Common complaint; algorithm quality issue with a clear reproducible trigger.",
    summary: "Single liked jazz song dominates recommendations; algorithm lacks nuance.",
    keyPhrases: ["jazz song", "exclusively forever", "algorithm", "zero nuance"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },
  {
    text: "the free tier ads are out of control. 3 unskippable ads between every song. you're not converting me to premium, you're converting me to apple music",
    title: null,
    rating: 1,
    source: "twitter",
    author: "@ad_free_dreams",
    daysAgo: 4,
    sentiment: "negative",
    sentimentScore: 0.9,
    theme: "pricing",
    subTheme: "ad_frequency",
    priority: "medium",
    priorityReason: "Churn risk to a named competitor; common free-tier sentiment.",
    summary: "Free-tier user threatens churn to Apple Music due to aggressive unskippable ads.",
    keyPhrases: ["free tier", "ads", "unskippable", "Apple Music", "premium"],
    isBug: false,
    isFeatureRequest: false,
    isActionable: true,
  },
  {
    text: "shoutout to whoever makes the 'Fans Also Like' section, found three new artists this week through it. more of that energy please @Spotify",
    title: null,
    rating: 4,
    source: "twitter",
    author: "@happy_listener",
    daysAgo: 5,
    sentiment: "positive",
    sentimentScore: 0.85,
    theme: "content",
    subTheme: "fans_also_like_success",
    priority: "low",
    priorityReason: "Positive feedback; informational. Signals which surfaces drive discovery.",
    summary: "User found three new artists via 'Fans Also Like'; wants more of that discovery energy.",
    keyPhrases: ["Fans Also Like", "three new artists", "more of that energy"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: false,
  },
  {
    text: "spotify premium and my songs still skip like a scratched cd in 2024. fix your app",
    title: null,
    rating: 1,
    source: "twitter",
    author: "@premium_but_skipping",
    daysAgo: 2,
    sentiment: "negative",
    sentimentScore: 0.92,
    theme: "performance",
    subTheme: "playback_skipping",
    priority: "high",
    priorityReason: "Premium user; public complaint about a core playback failure.",
    summary: "Premium user reports songs skipping like a scratched CD; demands a fix.",
    keyPhrases: ["premium", "songs still skip", "scratched cd", "fix your app"],
    isBug: true,
    isFeatureRequest: false,
    isActionable: true,
  },
  {
    text: "my daily mix has had the exact same songs for 3 months. i could literally predict the next track. boring",
    title: null,
    rating: 2,
    source: "twitter",
    author: "@predictable_mix",
    daysAgo: 6,
    sentiment: "negative",
    sentimentScore: 0.82,
    theme: "content",
    subTheme: "daily_mix_stale",
    priority: "medium",
    priorityReason: "Recurring theme; engagement risk on a flagship personalization feature.",
    summary: "Daily Mix unchanged for 3 months; user can predict the next track.",
    keyPhrases: ["daily mix", "exact same songs", "3 months", "predict", "boring"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },
  {
    text: "spotify has me in a chokehold of my own taste. i want OUT of my bubble but the algorithm won't let me leave",
    title: null,
    rating: 1,
    source: "twitter",
    author: "@trapped_in_bubble",
    daysAgo: 3,
    sentiment: "negative",
    sentimentScore: 0.87,
    theme: "content",
    subTheme: "filter_bubble",
    priority: "high",
    priorityReason: "Direct articulation of the core discovery pain point this project targets.",
    summary: "User feels trapped by the algorithm in their own taste bubble; wants escape.",
    keyPhrases: ["chokehold", "my own taste", "bubble", "algorithm", "won't let me leave"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },

  // ===== CSV Upload (2) ======================================================
  {
    text: "Have been a user for 8 years. The recommendation algorithm has noticeably degraded over the past 18 months. Same songs cycling. Considering switching.",
    title: "Long-time user, declining experience",
    rating: 3,
    source: "csv_upload",
    author: "csv_import_4921",
    daysAgo: 30,
    sentiment: "neutral",
    sentimentScore: 0.45,
    theme: "content",
    subTheme: "algorithm_decline",
    priority: "high",
    priorityReason: "Long-tenured user at churn risk; reports algorithm quality trend.",
    summary: "8-year user reports algorithm degradation over 18 months; considering switching.",
    keyPhrases: ["8 years", "recommendation algorithm", "degraded", "same songs", "switching"],
    isBug: false,
    isFeatureRequest: false,
    isActionable: true,
  },
  {
    text: "I travel a lot for work and need offline access. Downloads work but I can't browse or discover anything offline. Would love an 'offline discovery' playlist that updates when I'm online.",
    title: "Need offline discovery",
    rating: 2,
    source: "csv_upload",
    author: "csv_import_7788",
    daysAgo: 21,
    sentiment: "negative",
    sentimentScore: 0.7,
    theme: "reliability",
    subTheme: "offline_discovery_gap",
    priority: "medium",
    priorityReason: "Feature gap from a power-user segment; aligned with the discovery mission.",
    summary: "Frequent traveler wants an offline-friendly discovery playlist that refreshes when online.",
    keyPhrases: ["travel", "offline access", "browse", "discover", "offline discovery"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },

  // ===== Expansion (r4) — 55 additional reviews ==============================
  // Added in Task r4 to expand SEED_REVIEWS from 50 to 105. Grouped by source.
  // Distribution: google_play 18 · app_store 15 · reddit 12 · twitter 10.
  // -----------------------------------------------------------------------------

  // ----- Google Play (18) ----------------------------------------------------
  {
    text: "AI DJ keeps talking over the music and recommending the same five artists. I turned it off after two days. Just play the songs.",
    title: "AI DJ is annoying",
    rating: 1,
    source: "google_play",
    author: "Daniel V.",
    daysAgo: 4,
    sentiment: "negative",
    sentimentScore: 0.88,
    theme: "content",
    subTheme: "ai_dj_complaint",
    priority: "medium",
    priorityReason: "New flagship discovery feature generating negative feedback; opt-out request.",
    summary: "User finds AI DJ talkover annoying and recommendations repetitive; turned it off.",
    keyPhrases: ["AI DJ", "talking over", "same five artists", "turned it off"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },
  {
    text: "The Enhance button used to add genuinely new songs to my playlists. Now it just inserts tracks I already have in other playlists. Pointless feature.",
    title: "Enhance is broken",
    rating: 2,
    source: "google_play",
    author: "Stephanie L.",
    daysAgo: 19,
    sentiment: "negative",
    sentimentScore: 0.82,
    theme: "content",
    subTheme: "enhance_repetition",
    priority: "medium",
    priorityReason: "Personalization feature regression; reduces discovery value of the feature.",
    summary: "Enhance button now suggests songs user already owns; no longer adds new discovery value.",
    keyPhrases: ["Enhance button", "already have", "other playlists", "pointless"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },
  {
    text: "As a K-pop fan, Spotify's discovery is hit or miss. Sometimes it suggests amazing B-sides I missed, other times it just pushes the same group's title tracks over and over. Needs more variety.",
    title: "K-pop discovery needs work",
    rating: 3,
    source: "google_play",
    author: "Min-jun P.",
    daysAgo: 9,
    sentiment: "mixed",
    sentimentScore: 0.55,
    theme: "content",
    subTheme: "genre_bias",
    priority: "medium",
    priorityReason: "Genre-specific discovery gap; impacts a large global fan segment.",
    summary: "K-pop discovery inconsistent; surfaces B-sides sometimes but over-indexes on title tracks.",
    keyPhrases: ["K-pop", "B-sides", "title tracks", "variety"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },
  {
    text: "This year's Wrapped felt lazy. Same stats as last year, no new categories. The 'Sound Town' thing was weirdly inaccurate. Used to be my favorite day of the year.",
    title: "Wrapped was underwhelming",
    rating: 2,
    source: "google_play",
    author: "Greg H.",
    daysAgo: 45,
    sentiment: "negative",
    sentimentScore: 0.78,
    theme: "content",
    subTheme: "wrapped_disappointment",
    priority: "low",
    priorityReason: "Annual flagship moment underdelivered; sentiment trend to monitor for next cycle.",
    summary: "User disappointed by Wrapped; felt recycled and the Sound Town feature was inaccurate.",
    keyPhrases: ["Wrapped", "lazy", "same stats", "Sound Town", "inaccurate"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },
  {
    text: "Spotify crashes every time I connect to Android Auto in my Toyota. Reinstalled, cleared cache, nothing works. Google Play Music never had this issue. Fix it.",
    title: "Crashes on Android Auto",
    rating: 1,
    source: "google_play",
    author: "Robert K.",
    daysAgo: 2,
    sentiment: "negative",
    sentimentScore: 0.93,
    theme: "performance",
    subTheme: "android_auto_crash",
    priority: "critical",
    priorityReason: "Complete app failure in a common in-car scenario despite reinstall and cache clear.",
    summary: "App crashes on Android Auto connection in Toyota; no workaround resolves it.",
    keyPhrases: ["crashes", "Android Auto", "Toyota", "reinstalled", "cleared cache"],
    isBug: true,
    isFeatureRequest: false,
    isActionable: true,
  },
  {
    text: "Found an incredible synthwave playlist through the 'Fans Also Like' section on an artist page. Discovery can still be magic when it works. Just needs to happen more often.",
    title: "Great synthwave find",
    rating: 4,
    source: "google_play",
    author: "Nina R.",
    daysAgo: 14,
    sentiment: "positive",
    sentimentScore: 0.85,
    theme: "content",
    subTheme: "fans_also_like_success",
    priority: "low",
    priorityReason: "Positive feedback; informational. Signals which surfaces drive discovery.",
    summary: "User discovered a great synthwave playlist via 'Fans Also Like'; wants more frequent success.",
    keyPhrases: ["synthwave", "Fans Also Like", "artist page", "magic"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: false,
  },
  {
    text: "Family plan went up $3 and you added restrictions on who counts as 'family'. My adult son moved out for college and now I can't keep him on. Greedy.",
    title: "Family plan restrictions",
    rating: 2,
    source: "google_play",
    author: "Patricia M.",
    daysAgo: 27,
    sentiment: "negative",
    sentimentScore: 0.85,
    theme: "pricing",
    subTheme: "family_plan_restrictions",
    priority: "medium",
    priorityReason: "Pricing churn risk on a family-plan segment; explicit complaint about new restrictions.",
    summary: "Family plan price hike plus stricter address rules force user to remove college-age child.",
    keyPhrases: ["Family plan", "$3", "restrictions", "college", "greedy"],
    isBug: false,
    isFeatureRequest: false,
    isActionable: true,
  },
  {
    text: "Downloaded my Liked Songs (3000+ tracks) for a road trip. Woke up the next morning and they were all gone. Had to re-download over hotel WiFi. This bug has existed for years.",
    title: "Downloads vanished overnight",
    rating: 1,
    source: "google_play",
    author: "Carlos D.",
    daysAgo: 6,
    sentiment: "negative",
    sentimentScore: 0.92,
    theme: "reliability",
    subTheme: "download_disappearing",
    priority: "critical",
    priorityReason: "Premium feature failure with large library; long-standing reproducible bug.",
    summary: "3000+ downloaded Liked Songs vanished overnight; user forced to re-download over hotel WiFi.",
    keyPhrases: ["Downloaded", "Liked Songs", "3000+", "vanished", "road trip", "years"],
    isBug: true,
    isFeatureRequest: false,
    isActionable: true,
  },
  {
    text: "Search autocomplete is useless now. Type 'metal' and it suggests 'metallica' and 'metal pop'. Where are the deep genre results? Even YouTube Music does this better.",
    title: "Search autocomplete is bad",
    rating: 2,
    source: "google_play",
    author: "Erik J.",
    daysAgo: 16,
    sentiment: "negative",
    sentimentScore: 0.8,
    theme: "usability",
    subTheme: "autocomplete_shallow",
    priority: "medium",
    priorityReason: "Search discovery gap; user explicitly prefers a competitor for genre depth.",
    summary: "Search autocomplete returns shallow popular results instead of deep genre matches.",
    keyPhrases: ["autocomplete", "metal", "metallica", "deep genre", "YouTube Music"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },
  {
    text: "My Daily Mixes haven't changed in literally months. Same tracks, same order. I used to check them daily. Now I just play my own playlists. Bring back variety.",
    title: "Daily Mixes are frozen",
    rating: 2,
    source: "google_play",
    author: "Vanessa T.",
    daysAgo: 33,
    sentiment: "negative",
    sentimentScore: 0.84,
    theme: "content",
    subTheme: "daily_mix_stale",
    priority: "medium",
    priorityReason: "Recurring complaint; engaged user has abandoned a flagship personalization feature.",
    summary: "Daily Mixes unchanged for months; user has stopped checking them and plays own playlists.",
    keyPhrases: ["Daily Mixes", "months", "same order", "stopped checking", "variety"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },
  {
    text: "I listen to lo-fi while studying and now EVERY recommendation is lo-fi. I also like other genres! The algorithm can't tell the difference between background music and music I actually love.",
    title: "Lo-fi took over my recommendations",
    rating: 3,
    source: "google_play",
    author: "Yuki H.",
    daysAgo: 22,
    sentiment: "mixed",
    sentimentScore: 0.6,
    theme: "content",
    subTheme: "context_insensitive",
    priority: "high",
    priorityReason: "Algorithm context failure; impacts discovery quality across all genres for the user.",
    summary: "Background lo-fi listening dominates recommendations; algorithm cannot distinguish context.",
    keyPhrases: ["lo-fi", "studying", "recommendations", "background music", "context"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },
  {
    text: "The home screen is now 80% podcasts, audiobooks, and sponsored content. I just want to find music. Make a separate tab for non-music content already.",
    title: "Home screen is cluttered",
    rating: 2,
    source: "google_play",
    author: "Andre B.",
    daysAgo: 11,
    sentiment: "negative",
    sentimentScore: 0.83,
    theme: "usability",
    subTheme: "home_clutter_non_music",
    priority: "medium",
    priorityReason: "Usability issue; non-music content displaces music discovery on home surface.",
    summary: "Home screen dominated by podcasts/audiobooks/sponsored content; user wants separation.",
    keyPhrases: ["home screen", "podcasts", "audiobooks", "sponsored", "separate tab"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },
  {
    text: "Blend with my partner is genuinely delightful. We've discovered so much music we both love through it. Just wish it updated more than once a month.",
    title: "Blend is delightful",
    rating: 4,
    source: "google_play",
    author: "Maya S.",
    daysAgo: 18,
    sentiment: "positive",
    sentimentScore: 0.86,
    theme: "features",
    subTheme: "blend_playlist",
    priority: "low",
    priorityReason: "Positive engagement with social discovery feature; minor enhancement opportunity.",
    summary: "User loves Blend with partner for shared discovery; wants more frequent updates.",
    keyPhrases: ["Blend", "partner", "discovered", "shared music", "once a month"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },
  {
    text: "Audio quality is noticeably worse than Apple Music's lossless on a decent pair of headphones. Same price, worse sound. Why no lossless yet?",
    title: "No lossless audio",
    rating: 2,
    source: "google_play",
    author: "Thomas W.",
    daysAgo: 38,
    sentiment: "negative",
    sentimentScore: 0.78,
    theme: "content",
    subTheme: "no_lossless",
    priority: "low",
    priorityReason: "Long-standing competitive gap; not core to discovery mission but a churn factor.",
    summary: "User compares audio quality unfavorably to Apple Music lossless; wants lossless tier.",
    keyPhrases: ["audio quality", "Apple Music", "lossless", "same price", "headphones"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },
  {
    text: "Release Radar has been killing it lately. Found three new indie artists this month that I now can't stop playing. When Spotify's algorithm works, it's the best in the business.",
    title: "Release Radar delivering",
    rating: 5,
    source: "google_play",
    author: "Lila F.",
    daysAgo: 13,
    sentiment: "positive",
    sentimentScore: 0.9,
    theme: "content",
    subTheme: "release_radar_success",
    priority: "low",
    priorityReason: "Positive feedback; informational. Reinforces which surface drives discovery.",
    summary: "User discovered three new indie artists via Release Radar; praises the algorithm when it works.",
    keyPhrases: ["Release Radar", "indie artists", "three new", "best in the business"],
    isBug: false,
    isFeatureRequest: false,
    isActionable: false,
  },
  {
    text: "Crossfade randomly stopped working after the last update. Songs just cut off abruptly now. Tried toggling it on and off, reinstalling. Nothing fixes it. Annoying.",
    title: "Crossfade broken",
    rating: 1,
    source: "google_play",
    author: "Marcus B.",
    daysAgo: 5,
    sentiment: "negative",
    sentimentScore: 0.87,
    theme: "reliability",
    subTheme: "crossfade_regression",
    priority: "high",
    priorityReason: "Regression in a long-standing feature after an update; reproducible.",
    summary: "Crossfade stopped working after update; songs cut off abruptly despite toggling and reinstall.",
    keyPhrases: ["Crossfade", "stopped working", "update", "cut off", "reinstalling"],
    isBug: true,
    isFeatureRequest: false,
    isActionable: true,
  },
  {
    text: "Contrarian opinion: my Discover Weekly has been great this month. Found a bunch of indie folk artists I'd never heard of. Maybe it's genre-dependent?",
    title: "Discover Weekly is great for me",
    rating: 4,
    source: "google_play",
    author: "Ruth A.",
    daysAgo: 7,
    sentiment: "positive",
    sentimentScore: 0.82,
    theme: "content",
    subTheme: "discover_weekly_success",
    priority: "low",
    priorityReason: "Positive counter-signal; suggests Discover Weekly quality may vary by taste profile.",
    summary: "User reports Discover Weekly delivering great indie folk discoveries; speculates genre matters.",
    keyPhrases: ["Discover Weekly", "indie folk", "never heard of", "genre-dependent"],
    isBug: false,
    isFeatureRequest: false,
    isActionable: false,
  },
  {
    text: "I've skipped the same artist 50+ times and Spotify STILL recommends them. The 'not interested' button does nothing. Why even have the option?",
    title: "Skipping doesn't work",
    rating: 2,
    source: "google_play",
    author: "Phil C.",
    daysAgo: 24,
    sentiment: "negative",
    sentimentScore: 0.85,
    theme: "content",
    subTheme: "ignored_dismissal_signals",
    priority: "high",
    priorityReason: "Algorithm ignores explicit negative signals; undermines user trust in recommendations.",
    summary: "User skipped an artist 50+ times and 'not interested' does nothing; artist still recommended.",
    keyPhrases: ["skipped", "50+ times", "not interested", "still recommends", "does nothing"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },

  // ----- App Store (15) ------------------------------------------------------
  {
    text: "AI DJ is annoying. I don't need a fake voice telling me what I'm about to hear. Let me opt out of ever seeing it on the home screen.",
    title: "Let me disable AI DJ",
    rating: 1,
    source: "app_store",
    author: "ios_user_nyc",
    daysAgo: 3,
    sentiment: "negative",
    sentimentScore: 0.87,
    theme: "content",
    subTheme: "ai_dj_complaint",
    priority: "medium",
    priorityReason: "New feature generating opt-out requests; impacts home screen experience.",
    summary: "User finds AI DJ voice annoying and wants a permanent opt-out from the home screen.",
    keyPhrases: ["AI DJ", "fake voice", "opt out", "home screen"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },
  {
    text: "Blend playlists with my best friend are the best thing Spotify has added in years. We live in different countries now and it makes us feel connected through music.",
    title: "Blend connects us",
    rating: 5,
    source: "app_store",
    author: "sophie_p",
    daysAgo: 12,
    sentiment: "positive",
    sentimentScore: 0.9,
    theme: "features",
    subTheme: "blend_playlist",
    priority: "low",
    priorityReason: "Strong positive engagement with social discovery feature.",
    summary: "User loves Blend with long-distance best friend; feels connected through shared music.",
    keyPhrases: ["Blend", "best friend", "different countries", "connected", "music"],
    isBug: false,
    isFeatureRequest: false,
    isActionable: false,
  },
  {
    text: "Release Radar keeps suggesting songs I already saved weeks ago. It's supposed to show NEW releases. Used to be reliable, now it's just a recap.",
    title: "Release Radar is broken",
    rating: 2,
    source: "app_store",
    author: "mike_b",
    daysAgo: 8,
    sentiment: "negative",
    sentimentScore: 0.84,
    theme: "content",
    subTheme: "release_radar_repetition",
    priority: "high",
    priorityReason: "Flagship discovery feature broken; surfaces already-saved songs instead of new releases.",
    summary: "Release Radar suggests songs the user already saved; no longer surfaces new releases reliably.",
    keyPhrases: ["Release Radar", "already saved", "NEW releases", "recap", "reliable"],
    isBug: false,
    isFeatureRequest: false,
    isActionable: true,
  },
  {
    text: "App crashes after 30 seconds of playback on iOS 17.4. iPhone 13. Reinstalled twice. Cleared cache. Nothing works. I'm paying for Premium and can't even use the app.",
    title: "Crashes on iOS 17.4",
    rating: 1,
    source: "app_store",
    author: "frustrated_premium",
    daysAgo: 1,
    sentiment: "negative",
    sentimentScore: 0.95,
    theme: "performance",
    subTheme: "ios_crash",
    priority: "critical",
    priorityReason: "Complete app failure on a common iOS version/device; Premium user unable to use the app.",
    summary: "App crashes after 30 seconds on iOS 17.4 / iPhone 13 despite reinstall and cache clear.",
    keyPhrases: ["crashes", "30 seconds", "iOS 17.4", "iPhone 13", "Premium", "reinstalled"],
    isBug: true,
    isFeatureRequest: false,
    isActionable: true,
  },
  {
    text: "The new queue UI is awful. Can't reorder songs easily, can't see what's coming next without expanding. Why did you change something that worked perfectly?",
    title: "Queue UI is worse",
    rating: 2,
    source: "app_store",
    author: "alex_t",
    daysAgo: 15,
    sentiment: "negative",
    sentimentScore: 0.82,
    theme: "usability",
    subTheme: "queue_redesign_regression",
    priority: "medium",
    priorityReason: "Usability regression on a core playback flow with concrete friction examples.",
    summary: "New queue UI makes reordering and seeing upcoming songs harder; user wants the old design back.",
    keyPhrases: ["queue UI", "reorder", "what's coming next", "expanding", "worked perfectly"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },
  {
    text: "I have NEVER listened to a podcast on Spotify. Yet half my home page is podcasts. The algorithm should know that by now. Stop forcing this on me.",
    title: "Stop pushing podcasts",
    rating: 2,
    source: "app_store",
    author: "no_pods_pls",
    daysAgo: 20,
    sentiment: "negative",
    sentimentScore: 0.85,
    theme: "content",
    subTheme: "podcast_over_promotion",
    priority: "medium",
    priorityReason: "Persistent complaint; home page real estate wasted on never-engaged content type.",
    summary: "User who never listens to podcasts sees them dominate the home page; algorithm should adapt.",
    keyPhrases: ["NEVER", "podcast", "home page", "algorithm", "forcing"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },
  {
    text: "Classical music search is a disaster. Composer, conductor, orchestra, soloist — all jumbled. Can't filter properly. Apple Classical handles this way better.",
    title: "Classical search is broken",
    rating: 2,
    source: "app_store",
    author: "classical_listener",
    daysAgo: 17,
    sentiment: "negative",
    sentimentScore: 0.83,
    theme: "usability",
    subTheme: "classical_metadata",
    priority: "medium",
    priorityReason: "Search relevance gap for a specific large genre; competitor has a dedicated app.",
    summary: "Classical search jumbles composer/conductor/orchestra/soloist; user prefers Apple Classical.",
    keyPhrases: ["classical", "search", "composer", "conductor", "orchestra", "Apple Classical"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },
  {
    text: "Supergrouper is a fun idea but the playlist it generated was just the artists' most popular songs, not deeper cuts. Needs more thought to actually drive discovery.",
    title: "Supergrouper needs work",
    rating: 3,
    source: "app_store",
    author: "curious_listener",
    daysAgo: 26,
    sentiment: "mixed",
    sentimentScore: 0.55,
    theme: "content",
    subTheme: "supergrouper_shallow",
    priority: "low",
    priorityReason: "New feature with discovery potential but currently surfaces only popular tracks.",
    summary: "Supergrouper generates playlists of artists' most popular songs rather than deeper cuts.",
    keyPhrases: ["Supergrouper", "popular songs", "deeper cuts", "discovery"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },
  {
    text: "Got locked out of my Family plan because Spotify says my address 'doesn't match'. We literally live at the same address. Customer service was useless.",
    title: "Family plan address verification",
    rating: 2,
    source: "app_store",
    author: "locked_out_dad",
    daysAgo: 30,
    sentiment: "negative",
    sentimentScore: 0.86,
    theme: "pricing",
    subTheme: "family_plan_verification",
    priority: "medium",
    priorityReason: "Pricing/verification friction causing access loss; support escalation needed.",
    summary: "User locked out of Family plan due to false address mismatch; customer service unhelpful.",
    keyPhrases: ["Family plan", "locked out", "address", "doesn't match", "customer service"],
    isBug: false,
    isFeatureRequest: false,
    isActionable: true,
  },
  {
    text: "Spotify on Apple Watch still can't reliably play downloaded music without the phone nearby. What's the point of downloading to the watch? Garmin does this better.",
    title: "Apple Watch offline broken",
    rating: 1,
    source: "app_store",
    author: "runner_dave",
    daysAgo: 4,
    sentiment: "negative",
    sentimentScore: 0.88,
    theme: "reliability",
    subTheme: "apple_watch_offline_failure",
    priority: "high",
    priorityReason: "Premium feature failure on a popular wearable; competitor does it better.",
    summary: "Apple Watch can't reliably play downloaded music without phone nearby; user compares to Garmin.",
    keyPhrases: ["Apple Watch", "downloaded music", "phone nearby", "Garmin", "offline"],
    isBug: true,
    isFeatureRequest: false,
    isActionable: true,
  },
  {
    text: "Wrapped is genuinely my favorite marketing thing any company does. The storytelling, the shareability, the surprising stats. Flawless every year.",
    title: "Wrapped is the best",
    rating: 5,
    source: "app_store",
    author: "wrapped_fan",
    daysAgo: 50,
    sentiment: "positive",
    sentimentScore: 0.92,
    theme: "content",
    subTheme: "wrapped_experience",
    priority: "low",
    priorityReason: "Strong positive feedback on a flagship annual moment.",
    summary: "User praises Wrapped as the best marketing from any company; loves storytelling and shareability.",
    keyPhrases: ["Wrapped", "marketing", "storytelling", "shareability", "flawless"],
    isBug: false,
    isFeatureRequest: false,
    isActionable: false,
  },
  {
    text: "As a metal fan, discovery is hit or miss. Spotify's 'Metal Core' playlist is decent but it keeps suggesting the same 5 bands. There's so much underground metal out there.",
    title: "Metal discovery is shallow",
    rating: 3,
    source: "app_store",
    author: "metalhead_42",
    daysAgo: 21,
    sentiment: "mixed",
    sentimentScore: 0.55,
    theme: "content",
    subTheme: "genre_shallow",
    priority: "medium",
    priorityReason: "Genre-specific discovery gap; over-indexes on popular bands, misses underground.",
    summary: "Metal discovery surfaces same 5 bands; user wants more underground metal in recommendations.",
    keyPhrases: ["metal", "Metal Core", "same 5 bands", "underground", "discovery"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },
  {
    text: "I'm afraid to like songs now. One like and the algorithm overcorrects for weeks. Need a separate 'save without influencing recommendations' option.",
    title: "Afraid to like songs",
    rating: 2,
    source: "app_store",
    author: "cautious_listener",
    daysAgo: 9,
    sentiment: "negative",
    sentimentScore: 0.82,
    theme: "content",
    subTheme: "liked_songs_pollution",
    priority: "medium",
    priorityReason: "Core engagement mechanic now causes user anxiety; common complaint pattern.",
    summary: "User avoids liking songs to prevent recommendation pollution; wants a decoupled save option.",
    keyPhrases: ["afraid to like", "algorithm", "overcorrects", "save without influencing"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },
  {
    text: "5 ads in a row on the free tier. Five. I'm a student and can't afford Premium. Stop punishing free users, it just makes me want to leave entirely.",
    title: "Too many ads on free tier",
    rating: 1,
    source: "app_store",
    author: "broke_student_99",
    daysAgo: 7,
    sentiment: "negative",
    sentimentScore: 0.89,
    theme: "pricing",
    subTheme: "ad_frequency",
    priority: "medium",
    priorityReason: "Free-tier churn risk; aggressive ad cadence pushes users away rather than converting.",
    summary: "Free-tier user frustrated by 5 consecutive ads; cannot afford Premium and considers leaving.",
    keyPhrases: ["5 ads", "free tier", "student", "Premium", "punishing", "leave"],
    isBug: false,
    isFeatureRequest: false,
    isActionable: true,
  },
  {
    text: "Discover Weekly actually surprised me this week with a 2010s indie track I'd completely forgotten about. Genuinely great discovery when it works. More of this please.",
    title: "Discover Weekly surprised me",
    rating: 4,
    source: "app_store",
    author: "pleasantly_surprised",
    daysAgo: 11,
    sentiment: "positive",
    sentimentScore: 0.84,
    theme: "content",
    subTheme: "discover_weekly_success",
    priority: "low",
    priorityReason: "Positive counter-signal; shows Discover Weekly can still deliver serendipity.",
    summary: "User surprised by a forgotten indie track on Discover Weekly; wants more of this quality.",
    keyPhrases: ["Discover Weekly", "surprised", "indie track", "forgotten", "more of this"],
    isBug: false,
    isFeatureRequest: false,
    isActionable: false,
  },

  // ----- Reddit (12) ---------------------------------------------------------
  {
    text: "Anyone else's Spotify basically become a static radio station? Mine hasn't changed in months regardless of what I do. Starting to wonder if the algorithm is even updating for me.",
    title: null,
    rating: 1,
    source: "reddit",
    author: "u/static_station",
    daysAgo: 5,
    sentiment: "negative",
    sentimentScore: 0.86,
    theme: "content",
    subTheme: "algorithm_rut",
    priority: "high",
    priorityReason: "Community thread validating algorithm stagnation; likely a broad issue.",
    summary: "User reports Spotify has become static regardless of engagement; questions if algorithm updates.",
    keyPhrases: ["static radio", "hasn't changed", "months", "algorithm updating"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },
  {
    text: "Am I the only one who hates the AI DJ? The voice is cringe, the picks are generic, and it keeps interrupting actual music. Let me disable it permanently.",
    title: null,
    rating: 2,
    source: "reddit",
    author: "u/dj_hater",
    daysAgo: 10,
    sentiment: "negative",
    sentimentScore: 0.85,
    theme: "content",
    subTheme: "ai_dj_complaint",
    priority: "medium",
    priorityReason: "New flagship feature generating persistent negative feedback; opt-out request.",
    summary: "User hates AI DJ voice and generic picks; wants permanent disable option.",
    keyPhrases: ["AI DJ", "cringe", "generic", "interrupting", "disable permanently"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },
  {
    text: "Used to look forward to Mondays. Now Discover Weekly is just songs I already know or stuff adjacent to what I have. Anyone found a better discovery tool?",
    title: "Discover Weekly is dead",
    rating: 3,
    source: "reddit",
    author: "u/miss_mondays",
    daysAgo: 14,
    sentiment: "neutral",
    sentimentScore: 0.45,
    theme: "content",
    subTheme: "discover_weekly_decline",
    priority: "medium",
    priorityReason: "Sentiment trend on flagship feature; engaged user seeking alternatives.",
    summary: "Discover Weekly no longer surprises; user seeking alternative discovery tools.",
    keyPhrases: ["Mondays", "Discover Weekly", "songs I already know", "adjacent", "discovery tool"],
    isBug: false,
    isFeatureRequest: false,
    isActionable: true,
  },
  {
    text: "Downloaded songs won't play offline anymore since the last update. Shows the green arrow but won't play without signal. Tried everything. Anyone else?",
    title: null,
    rating: 1,
    source: "reddit",
    author: "u/green_arrow_bug",
    daysAgo: 7,
    sentiment: "negative",
    sentimentScore: 0.9,
    theme: "reliability",
    subTheme: "offline_playback_failure",
    priority: "critical",
    priorityReason: "Regression in offline playback after update; reproducible; affects Premium feature.",
    summary: "Downloaded songs show green arrow but won't play offline since last update.",
    keyPhrases: ["Downloaded", "offline", "green arrow", "won't play", "update"],
    isBug: true,
    isFeatureRequest: false,
    isActionable: true,
  },
  {
    text: "No matter what I do, I can't escape my own taste profile. Even when I explicitly search for new genres, recommendations pull me back. The filter bubble is real.",
    title: "Trapped in my own taste",
    rating: 2,
    source: "reddit",
    author: "u/cant_escape",
    daysAgo: 11,
    sentiment: "negative",
    sentimentScore: 0.84,
    theme: "content",
    subTheme: "filter_bubble",
    priority: "high",
    priorityReason: "Direct articulation of the core discovery pain point this project targets.",
    summary: "User cannot escape their taste profile; recommendations always pull back to familiar genres.",
    keyPhrases: ["taste profile", "new genres", "recommendations", "filter bubble", "can't escape"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },
  {
    text: "Daily Mixes used to refresh weekly. Now they're basically frozen. Mine has had the same 50 songs for 3 months. Anyone know if there's a way to force a refresh?",
    title: null,
    rating: 3,
    source: "reddit",
    author: "u/frozen_mix",
    daysAgo: 18,
    sentiment: "mixed",
    sentimentScore: 0.58,
    theme: "content",
    subTheme: "daily_mix_stale",
    priority: "medium",
    priorityReason: "Recurring complaint; engaged user seeking workarounds for staleness.",
    summary: "Daily Mixes frozen for 3 months with same 50 songs; user seeks a way to force refresh.",
    keyPhrases: ["Daily Mixes", "refresh", "frozen", "50 songs", "3 months", "force a refresh"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },
  {
    text: "K-pop fan here. Spotify's recommendations are weirdly biased toward a few big groups. There's so much more K-pop out there. Why only suggest BTS and Blackpink adjacent stuff?",
    title: null,
    rating: 3,
    source: "reddit",
    author: "u/kpop_deepcuts",
    daysAgo: 13,
    sentiment: "mixed",
    sentimentScore: 0.55,
    theme: "content",
    subTheme: "genre_bias",
    priority: "medium",
    priorityReason: "Genre-specific discovery gap; large global fan segment underserved.",
    summary: "K-pop recommendations over-index on BTS/Blackpink adjacent artists; misses deeper catalog.",
    keyPhrases: ["K-pop", "biased", "BTS", "Blackpink", "adjacent"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },
  {
    text: "Spotify Connect keeps disconnecting from my Sonos mid-song. Has to reconnect, then plays from the start of the song. Infuriating. Worked fine a year ago.",
    title: null,
    rating: 1,
    source: "reddit",
    author: "u/sonos_pain",
    daysAgo: 6,
    sentiment: "negative",
    sentimentScore: 0.88,
    theme: "reliability",
    subTheme: "connect_disconnect",
    priority: "high",
    priorityReason: "Reproducible regression on a popular speaker ecosystem; impacts listening flow.",
    summary: "Spotify Connect disconnects from Sonos mid-song and restarts track on reconnect.",
    keyPhrases: ["Spotify Connect", "Sonos", "disconnecting", "mid-song", "reconnect", "regression"],
    isBug: true,
    isFeatureRequest: false,
    isActionable: true,
  },
  {
    text: "Friend activity feed on desktop is the best discovery feature Spotify has. WHY is it not on mobile? I'd discover so much more if I could see what friends are playing on the go.",
    title: "Bring friend activity to mobile",
    rating: 4,
    source: "reddit",
    author: "u/social_discovery",
    daysAgo: 22,
    sentiment: "positive",
    sentimentScore: 0.82,
    theme: "features",
    subTheme: "friend_activity_feed",
    priority: "medium",
    priorityReason: "Feature parity gap; high-value discovery surface missing on mobile.",
    summary: "User loves desktop friend activity feed; wants it on mobile for on-the-go discovery.",
    keyPhrases: ["friend activity", "desktop", "mobile", "discovery", "what friends are playing"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },
  {
    text: "Listened to a lo-fi study playlist ONCE and now 70% of my recommendations are lo-fi. I like metal and jazz normally! The algorithm has no idea what I actually enjoy.",
    title: null,
    rating: 2,
    source: "reddit",
    author: "u/lo-fi_cursed",
    daysAgo: 9,
    sentiment: "negative",
    sentimentScore: 0.86,
    theme: "content",
    subTheme: "context_insensitive",
    priority: "high",
    priorityReason: "Algorithm overcorrects from a single context; impacts discovery for the user's actual tastes.",
    summary: "One lo-fi playlist listening session caused 70% of recommendations to become lo-fi.",
    keyPhrases: ["lo-fi", "study playlist", "70%", "recommendations", "metal and jazz", "algorithm"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },
  {
    text: "Found my now-favorite indie artist through a random 'Fans Also Like' click three years ago. Spotify CAN be amazing for discovery. Just wish it happened more consistently.",
    title: null,
    rating: 5,
    source: "reddit",
    author: "u/serendipitous_find",
    daysAgo: 16,
    sentiment: "positive",
    sentimentScore: 0.88,
    theme: "content",
    subTheme: "fans_also_like_success",
    priority: "low",
    priorityReason: "Positive feedback; informational. Reinforces which surface drives long-term discovery.",
    summary: "User found favorite indie artist via 'Fans Also Like' 3 years ago; wants more consistent discovery.",
    keyPhrases: ["indie artist", "Fans Also Like", "three years", "amazing", "consistently"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: false,
  },
  {
    text: "Honestly questioning if Premium is worth it. Price keeps going up, features keep getting paywalled separately, audio quality hasn't improved. What am I actually paying for?",
    title: "Is Premium worth it anymore?",
    rating: 3,
    source: "reddit",
    author: "u/value_questioner",
    daysAgo: 25,
    sentiment: "neutral",
    sentimentScore: 0.42,
    theme: "pricing",
    subTheme: "premium_value_erosion",
    priority: "medium",
    priorityReason: "Churn-risk sentiment from a paying user; value perception eroding.",
    summary: "Premium user questioning value as price rises and features get separately paywalled.",
    keyPhrases: ["Premium", "worth it", "price keeps going up", "paywalled", "audio quality"],
    isBug: false,
    isFeatureRequest: false,
    isActionable: true,
  },

  // ----- Twitter (10) --------------------------------------------------------
  {
    text: "spotify's AI DJ is the most annoying feature they've ever shipped. i don't need a robot to narrate my music. let me opt out permanently",
    title: null,
    rating: 2,
    source: "twitter",
    author: "@anti_dj",
    daysAgo: 2,
    sentiment: "negative",
    sentimentScore: 0.86,
    theme: "content",
    subTheme: "ai_dj_complaint",
    priority: "medium",
    priorityReason: "New feature generating persistent negative feedback; opt-out request, viral-style.",
    summary: "User calls AI DJ the most annoying Spotify feature ever; wants permanent opt-out.",
    keyPhrases: ["AI DJ", "annoying", "robot", "narrate", "opt out"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },
  {
    text: "discover weekly used to be the highlight of my week. now it's just songs i already have saved. spotify killed their best feature",
    title: null,
    rating: 1,
    source: "twitter",
    author: "@monday_mourner",
    daysAgo: 4,
    sentiment: "negative",
    sentimentScore: 0.9,
    theme: "content",
    subTheme: "discover_weekly_decline",
    priority: "high",
    priorityReason: "Flagship feature regression; public viral-style complaint, signals broad sentiment.",
    summary: "User mourns Discover Weekly; now surfaces already-saved songs instead of new discoveries.",
    keyPhrases: ["discover weekly", "highlight", "already saved", "killed", "best feature"],
    isBug: false,
    isFeatureRequest: false,
    isActionable: true,
  },
  {
    text: "wrapped season is the only time spotify's marketing actually matches the product. genuinely look forward to it every year. flawlessly executed",
    title: null,
    rating: 5,
    source: "twitter",
    author: "@wrapped_stan",
    daysAgo: 35,
    sentiment: "positive",
    sentimentScore: 0.9,
    theme: "content",
    subTheme: "wrapped_experience",
    priority: "low",
    priorityReason: "Strong positive feedback on flagship annual moment.",
    summary: "User praises Wrapped as flawless; only time marketing matches the product.",
    keyPhrases: ["wrapped", "marketing", "matches the product", "look forward", "flawlessly"],
    isBug: false,
    isFeatureRequest: false,
    isActionable: false,
  },
  {
    text: "spotify has decided i like 12 songs and refuses to recommend anything else. i am trapped in algorithm jail",
    title: null,
    rating: 1,
    source: "twitter",
    author: "@algorithm_jail",
    daysAgo: 6,
    sentiment: "negative",
    sentimentScore: 0.88,
    theme: "content",
    subTheme: "filter_bubble",
    priority: "high",
    priorityReason: "Direct articulation of the core discovery pain point; viral-style complaint.",
    summary: "User feels trapped by algorithm recommending only the same 12 songs.",
    keyPhrases: ["12 songs", "refuses", "recommend", "trapped", "algorithm jail"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },
  {
    text: "liking a song on spotify is a hostage negotiation. you get one bad like and your recommendations are poisoned for months",
    title: null,
    rating: 2,
    source: "twitter",
    author: "@like_button_fear",
    daysAgo: 3,
    sentiment: "negative",
    sentimentScore: 0.87,
    theme: "content",
    subTheme: "liked_songs_pollution",
    priority: "medium",
    priorityReason: "Common complaint; viral-style framing, signals core mechanic anxiety.",
    summary: "User likens liking a song to a hostage negotiation; one bad like poisons recommendations for months.",
    keyPhrases: ["liking", "hostage negotiation", "bad like", "recommendations", "poisoned"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },
  {
    text: "my daily mix has had the same songs for so long i've memorized the order. it's not a 'mix', it's a playlist at this point",
    title: null,
    rating: 2,
    source: "twitter",
    author: "@predictable_mix2",
    daysAgo: 8,
    sentiment: "negative",
    sentimentScore: 0.83,
    theme: "content",
    subTheme: "daily_mix_stale",
    priority: "medium",
    priorityReason: "Recurring theme; engagement risk on a flagship personalization feature.",
    summary: "Daily Mix unchanged so long user memorized the order; calls it a playlist, not a mix.",
    keyPhrases: ["daily mix", "same songs", "memorized", "order", "playlist"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },
  {
    text: "blend playlists with my long distance partner are genuinely the best thing spotify has made. we discover music together even when apart",
    title: null,
    rating: 4,
    source: "twitter",
    author: "@ldr_blend",
    daysAgo: 12,
    sentiment: "positive",
    sentimentScore: 0.87,
    theme: "features",
    subTheme: "blend_playlist",
    priority: "low",
    priorityReason: "Strong positive engagement with social discovery feature.",
    summary: "User praises Blend with long-distance partner as best Spotify feature for shared discovery.",
    keyPhrases: ["blend", "long distance", "partner", "discover together", "apart"],
    isBug: false,
    isFeatureRequest: false,
    isActionable: false,
  },
  {
    text: "spotify has been crashing on android auto every single commute this week. tried everything. this is a premium subscription i can't even use",
    title: null,
    rating: 1,
    source: "twitter",
    author: "@commuter_nightmare",
    daysAgo: 1,
    sentiment: "negative",
    sentimentScore: 0.92,
    theme: "performance",
    subTheme: "android_auto_crash",
    priority: "critical",
    priorityReason: "Complete app failure in a common in-car scenario for a Premium subscriber.",
    summary: "Spotify crashes on Android Auto every commute; Premium user unable to use subscription.",
    keyPhrases: ["crashing", "android auto", "commute", "premium", "can't even use"],
    isBug: true,
    isFeatureRequest: false,
    isActionable: true,
  },
  {
    text: "spotify still capping at 320kbps in 2024 while tidal and apple music offer lossless for the same price. embarrassing",
    title: null,
    rating: 2,
    source: "twitter",
    author: "@bitrate_shamer",
    daysAgo: 14,
    sentiment: "negative",
    sentimentScore: 0.8,
    theme: "content",
    subTheme: "no_lossless",
    priority: "low",
    priorityReason: "Long-standing competitive gap; viral-style public shaming.",
    summary: "User shames Spotify for 320kbps cap while competitors offer lossless at the same price.",
    keyPhrases: ["320kbps", "tidal", "apple music", "lossless", "same price", "embarrassing"],
    isBug: false,
    isFeatureRequest: true,
    isActionable: true,
  },
  {
    text: "counterpoint: my discover weekly has been incredible lately. found 3 new indie artists this month. y'all need to listen to more varied music",
    title: null,
    rating: 4,
    source: "twitter",
    author: "@defending_dw",
    daysAgo: 9,
    sentiment: "positive",
    sentimentScore: 0.83,
    theme: "content",
    subTheme: "discover_weekly_success",
    priority: "low",
    priorityReason: "Positive counter-signal; suggests Discover Weekly quality may vary by user behavior.",
    summary: "User defends Discover Weekly; found 3 new indie artists this month.",
    keyPhrases: ["discover weekly", "incredible", "3 new indie artists", "varied music"],
    isBug: false,
    isFeatureRequest: false,
    isActionable: false,
  },
];

// -----------------------------------------------------------------------------
// SEED_COLLECTOR_SOURCES
// -----------------------------------------------------------------------------
// Four default automated collector sources, one per supported source type.
// `config` is a JSON-encoded string (matches the CollectorSource.config column).
// -----------------------------------------------------------------------------

export const SEED_COLLECTOR_SOURCES: SeedCollectorSourceDef[] = [
  {
    sourceType: "google_play",
    name: "Spotify — Google Play Reviews",
    config: JSON.stringify({ appId: "com.spotify.music", lang: "en", sort: "newest" }),
    enabled: true,
    schedule: "0 9 * * *", // daily at 09:00
    lastRunAt: hoursAgo(2),
    lastRunStatus: "success",
    lastRunCount: 24,
    totalCollected: 1840,
  },
  {
    sourceType: "app_store",
    name: "Spotify — App Store Reviews (US)",
    config: JSON.stringify({ appId: "324684580", country: "us" }),
    enabled: true,
    schedule: "30 9 * * *", // daily at 09:30
    lastRunAt: hoursAgo(3),
    lastRunStatus: "success",
    lastRunCount: 18,
    totalCollected: 2105,
  },
  {
    sourceType: "reddit",
    name: "r/spotify — Hot Posts",
    config: JSON.stringify({ subreddit: "spotify", sort: "hot", limit: 100 }),
    enabled: true,
    schedule: "0 */6 * * *", // every 6 hours
    lastRunAt: hoursAgo(1),
    lastRunStatus: "partial",
    lastRunCount: 42,
    totalCollected: 876,
  },
  {
    sourceType: "twitter",
    name: "Spotify Discovery Mentions",
    config: JSON.stringify({
      query: "spotify discovery OR spotify recommendations",
      limit: 100,
    }),
    enabled: true,
    schedule: "0 */4 * * *", // every 4 hours
    lastRunAt: hoursAgo(4),
    lastRunStatus: "success",
    lastRunCount: 67,
    totalCollected: 1245,
  },
];

// -----------------------------------------------------------------------------
// seedDatabase
// -----------------------------------------------------------------------------
// Wipes all existing data (CollectorLog → CollectorSource → Review → Project)
// and inserts one project, all SEED_REVIEWS (with pre-computed AI analysis),
// and the four SEED_COLLECTOR_SOURCES. Returns high-level counts.
//
// The PrismaClient is passed in by the caller (the /api/seed route) — this
// module imports the type only, never instantiates the client itself.
// -----------------------------------------------------------------------------

export async function seedDatabase(db: PrismaClient): Promise<{
  project: any;
  reviewsInserted: number;
  sourcesInserted: number;
  user: { id: string; email: string; name: string } | null;
}> {
  // 1. Wipe existing data. Order respects FK constraints.
  await db.activityLog.deleteMany();
  await db.webhookDelivery.deleteMany();
  await db.webhookConfig.deleteMany();
  await db.reportSchedule.deleteMany();
  await db.analyticsDaily.deleteMany();
  await db.savedSearch.deleteMany();
  await db.insight.deleteMany();
  await db.chatMessage.deleteMany();
  await db.uploadBatch.deleteMany();
  await db.apiKey.deleteMany();
  await db.reviewEmbedding.deleteMany();
  await db.collectorLog.deleteMany();
  await db.collectorSource.deleteMany();
  await db.review.deleteMany();
  await db.projectMember.deleteMany();
  await db.project.deleteMany();
  await db.user.deleteMany();
  await db.activityLog.deleteMany();

  // 2. Create the default admin user (scrypt-hashed password).
  //    Login: pm@reviewpulse.dev / ReviewPulse123!
  const { hashPassword } = await import("./auth");
  const admin = await db.user.create({
    data: {
      email: "pm@reviewpulse.dev",
      name: "Product Manager",
      passwordHash: hashPassword("ReviewPulse123!"),
      authProvider: "email",
    },
  });

  // 3. Create the project owned by the admin user + admin membership.
  const project = await db.project.create({
    data: {
      name: "Spotify — Music Discovery",
      description:
        "Growth team initiative: analyze user feedback to increase meaningful music discovery. PM Fellowship graduation project, June 2026.",
      ownerId: admin.id,
      members: { create: { userId: admin.id, role: "admin" } },
    },
  });

  // 3b. Seed two extra team members so the Team page has real data.
  const aisha = await db.user.create({
    data: {
      email: "aisha@reviewpulse.dev",
      name: "Aisha Rahman",
      passwordHash: hashPassword("AnalystPass1!"),
      authProvider: "email",
    },
  });
  await db.projectMember.create({
    data: { projectId: project.id, userId: aisha.id, role: "analyst", invitedBy: admin.id },
  });
  const marco = await db.user.create({
    data: {
      email: "marco@reviewpulse.dev",
      name: "Marco Bianchi",
      passwordHash: hashPassword("AnalystPass1!"),
      authProvider: "email",
    },
  });
  await db.projectMember.create({
    data: { projectId: project.id, userId: marco.id, role: "viewer", invitedBy: admin.id },
  });

  // 4. Insert all seed reviews with pre-computed AI analysis fields.
  const nowMs = Date.now();
  await db.review.createMany({
    data: SEED_REVIEWS.map((r) => ({
      projectId: project.id,
      text: r.text,
      title: r.title,
      rating: r.rating,
      reviewDate: new Date(nowMs - r.daysAgo * MS_PER_DAY),
      source: r.source,
      author: r.author,
      contentHash: createHash("sha256").update(r.text).digest("hex"),
      processingStatus: "completed",
      processedAt: new Date(),
      sentiment: r.sentiment,
      sentimentScore: r.sentimentScore,
      theme: r.theme,
      subTheme: r.subTheme,
      priority: r.priority,
      priorityReason: r.priorityReason,
      summary: r.summary,
      keyPhrases: JSON.stringify(r.keyPhrases),
      isBug: r.isBug,
      isFeatureRequest: r.isFeatureRequest,
      isActionable: r.isActionable,
    })),
  });

  // 5. Insert the four collector sources under the project.
  await db.collectorSource.createMany({
    data: SEED_COLLECTOR_SOURCES.map((s) => ({
      projectId: project.id,
      sourceType: s.sourceType,
      name: s.name,
      config: s.config,
      enabled: s.enabled,
      schedule: s.schedule,
      lastRunAt: s.lastRunAt,
      lastRunStatus: s.lastRunStatus,
      lastRunCount: s.lastRunCount,
      totalCollected: s.totalCollected,
    })),
  });

  return {
    project,
    reviewsInserted: SEED_REVIEWS.length,
    sourcesInserted: SEED_COLLECTOR_SOURCES.length,
    user: { id: admin.id, email: admin.email, name: admin.name },
  };
}
